### ISSUE TITLE
Simple RFID Authentication

### ISSUE THREAD

**Issue by jshum1** [OpenEVSE/ESP32_WiFi_V4.x#133]
I would like to add capability to perform simple access control using RFID cards - I have several neighbors that will use my charger, and would like access control, plus a fairly easy method of querying energy consumption per user.  I have an OpenEVSE kit on the way to be installed next week, and I ordered a simple MFRC522 board to pair with it.  I could probably get it working with a separate Arduino board and MQTT, but it would be nice to interface directly to the ESP32 in the OpenEVSE kit.  If I get a chance to try it out, is there a preferred method of implementing?  Where in the charging flow diagram should access control be inserted?  Also, the board connects via SPI - any issues with that?  There is supposedly a way to force I2C mode out of the board if that's preferable.

**Comment by jeremypoulter** [comment]
There is now a PR open to add support for RFID, #146

**Comment by jeremypoulter** [comment]
Now #167
