### ISSUE TITLE
Unable to connect to (non-secure/1883) MQTT broker without enabling "Reject self-signed certificates"

### ISSUE THREAD

**Issue by ethan4** [OpenEVSE/ESP32_WiFi_V4.x#136]
I've found that if I try to connect to my broker on the non secure port, with the address set to mqtt NOT mqtts this will fail if I have the check box for "Reject self-signed certificates" disabled.

In the mosquitto log I get a SOCKET error warning. This is also the same warning I get if I try to connect on the MQTTS port which works properly with a valid certificate from Lets Encrypt so perhaps the first time I tried to configure MQTTS and failed there is now a stuck parameter or similar which is causing a problem.

**Comment by ethan4** [comment]
See issue #137 for a related problem.

**Comment by jeremypoulter** [comment]
Hum... I thought we had fixed this issue... jeremypoulter/ArduinoMongoose#13. Need to check we are using that fix
