### ISSUE TITLE
DEV V4.0: LCD does not update max current in 'Ready' mode  

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#140]
In 'Ready or mode the LCD displays "Ready 32A". However, if the maximum current is adjusted on the interface e.g 6A the LCD still shows 32A. I think this is because the Pilot value still seems to be 32A: 

![OpenEVSE](https://user-images.githubusercontent.com/758844/106687078-5b511280-65c3-11eb-8ff0-6285e5372416.png)

**Comment by TheBluProject** [comment]
Seems like similiar issue to the lifetime kWh update, it actually gets sent to EVSE but does not show on the GUI until the restart of the WiFi module - seems like the value is only retrieved upon the init / start

**Comment by glynhudson** [comment]
This is still an issue in the latest version. It's quite a important and potentially serious issue since being able to see the max current of the unit before connecting can be critical for some use cases and confusing for many others. The LCD max current should update to reflect the max current setting.  

![20210506_194229-COLLAGE_2](https://user-images.githubusercontent.com/758844/117349700-9bb27c00-aea3-11eb-956f-eb59f6af3bf7.jpg)

**Comment by rbray89** [comment]
Ah. Grateful to finally see that I'm not crazy. I can confirm this is an issue on the current release. This is rather important for me, as the pilot amperage retrieved from MQTT is never updated, so I can't create my intelligent circuit sharing system until this is resolved.
