### ISSUE TITLE
DEV V4.0: LCD and WiFi display date in different formats.

### ISSUE THREAD

**Issue by chris1howell** [OpenEVSE/ESP32_WiFi_V4.x#144]
Web interface displays date in Month/Day/Year format
LCD displays date in Day/Month/Year format.

Both should use the same format. Optional, LCD could display a friendly format such as Month Day such as September 25 without the year

**Comment by glynhudson** [comment]
For simplicity do you think it's important for the LCD to show the date? I'm not sure if it's required or useful to be displayed on the LCD? Obviously the more things the LCD has to cycle through the longer a user will have to wait to see the info they want!

**Comment by chris1howell** [comment]
Good point. Date is probably not necessary.

**Comment by glynhudson** [comment]
I agree, let's remove the date.
