### ISSUE TITLE
DEV V4.0 MQTT Voltage topic is not followed.

### ISSUE THREAD

**Issue by slavkobrzeg** [OpenEVSE/ESP32_WiFi_V4.x#160]
Hey guys! Wonderful job, thanks!!!
Today I realized that even if I have the correct Voltage topic set - I haven't changed it since I use OpeEVSE - the main page shows me 240V which is the default setting when we do not have any real value to track. 
![image](https://user-images.githubusercontent.com/45559778/109959125-5e850e80-7ce7-11eb-81cc-c91f41a2bf61.png)
It was working like a charm on V3.
![image](https://user-images.githubusercontent.com/45559778/109959185-6ba1fd80-7ce7-11eb-85ed-876fb623b792.png)

**Comment by jeremypoulter** [comment]
Hum, weird I was looking at this only last night, I think it was working, I will double check however

**Comment by slavkobrzeg** [comment]
The pilot info is also wrong. Doesn't follow the set value. And the MQTT message doesn't contain all information, but I think there is a new separate bug on that.

**Comment by glynhudson** [comment]
I confirm I can also replicate this issue. Well spotted. 'Voltage' is always 240V regardless of the MQTT input

**Comment by ayasystems** [comment]
Here the same problem. Voltage is always 240

**Comment by glynhudson** [comment]
This should be fixed in V4.0.1 , what FW version are you running? https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/tag/4.0.1

**Comment by ayasystems** [comment]
Hi

I'm sorry, you are right. I was wrong because voltage is updated only when is charging....

Yes, I'm in 4.1

Should be closed the issue, thanks!
