### ISSUE TITLE
Add GUI to configure LED brightness

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP32_WiFi_V4.x#162]

**Comment by joshchernoff** [comment]
I really like this idea, that plus disable LCD and LED altogether. I live in a populated area and would rather have my unit outside of the garage if not for this.

**Comment by glynhudson** [comment]
Very good idea. The new NeoPixel LED's are super bright! Being able to turn them off or reduce brightness would be great.

**Comment by jeremypoulter** [comment]
The LED Brightness is done, LCD is covered in #8
