### ISSUE TITLE
Implement OCPP protocol V1.6

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#175]
Open Charge Point Protocol: http://www.openchargealliance.org/protocols/ocpp/ocpp-16/

Allow OpenEVSE to integrate easily with other charging networks. 

Spec attached: 
[ocpp-1.6_edition_2.pdf](https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/files/1408057/ocpp-1.6_edition_2.pdf)
[OCPP_1.6_JSON_Specification.pdf](https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/files/1408058/OCPP_1.6_JSON_Specification.pdf)

Wiki page: https://github.com/OpenEVSE/openevse_wifi_server/wiki/Open-Charge-Point-Protocol

**Comment by EvChargepoints** [comment]
Hi Glynn I hope all is well. Was you aware we was copied in to this ? 

Best Regards 

Paul Delahay

**Comment by jeremypoulter** [comment]
This was just moved from the v2 project and you had commented on that thread. As you are still alive, please can you pay the nearly £2000 you owe me?

**Comment by chuck-h** [comment]
@matth-x Props for your work on this!!
I am curious where current control over OCPP (e.g. reduce charging current if electrical service is overloaded) fits in to your plans. I have started experimenting with this on the host side using a SteVe add-on. The OCPP 1.6 Smart Charging support (SetChargingProfile etc) seems awfully complex.
I may be able to help with implementing it if desired.

**Comment by matth-x** [comment]
Smart Charging was actually the central concern of this project when I started it. The library fully supports the `SetChargingProfile` operation for the single connector use case. You can find an example [here](https://github.com/matth-x/ArduinoOcpp/blob/be15473ef90fb94ea1c3a6ef9c886946ceba8a5f/examples/ESP32/main.ino#L48) on how to integrate that functionality into your charger.

Btw. thank you for the nice comment. If you have further questions, don't hesitate to ask (also possible via [private message](https://github.com/matth-x/ArduinoOcpp#further-help)). If you like to share your ideas, I would be curious to learn about them.

**Comment by glynhudson** [comment]
Thanks to @matth-x for implementing basic OCPP implementation in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/182

The latest version is available in V4.1.0 release (currently in beta).

Testing feedback of the beta would be appreciated, it's probably best to open new issues for specific issues from now on: https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/tag/4.1.0
