### ISSUE TITLE
Sensor Value: Pilot not reflecting right value > 11A

### ISSUE THREAD

**Issue by lebsd** [OpenEVSE/ESP32_WiFi_V4.x#178]
Not certain what is the source data for the value Pilot under the Sensor block display but seems to be inconsistent and perhaps misleading since there is no sensor I am aware for the Pilot.

While operating in Eco Mode, with no timers, and a maximum Value set to 16A under Setup, noticed that the Session current reflects ~16A, but the Sensor Pilot Value seems not to increase above 11A. Checked my Tesla for charging current and it shows 16A.    Also Current Value under Session Status ~16A.

**Comment by glynhudson** [comment]
Is this still an issue in the latest 4.01 version? https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/tag/4.0.1

I've not noticed this issue.

**Comment by jeremypoulter** [comment]
I think it will be, several bits of the UI are still getting values directly from the EVSE via RAPI, including the pilot value. As this may not be updated as the value is changed by the WIFi module it is not guaranteed to be correct

**Comment by glynhudson** [comment]
Ah ok, I am able to replicate the issue. I think we should remove the 'pilot' reading from the sensors display since as the OP mentions it's not really a sensor and is not really needed. Please ignore the reading it for the moment.

**Comment by glynhudson** [comment]
Related issue to https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/140
