### ISSUE TITLE
Uploading ESP32_WiFi_V4 /littlefs/schedule.json does not exist error

### ISSUE THREAD

**Issue by krupis** [OpenEVSE/ESP32_WiFi_V4.x#183]
Hello. I am learning about programming and came across this project. I would like to explore more about it therefore I have downloaded the project and setup my platformio extension on VS code. I have sucesfully built the code and uploaded it to my ESP32 development board.

After uploading, I went to serial monitor and restarted the device, and I have received error message:

```
--- Available ports:
---  1: COM3                 'USB Serial Port (COM3)'
---  2: COM11                'Silicon Labs CP210x USB to UART Bridge (COM11)'
--- Enter port index or full name: 2
--- Miniterm on COM11  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:804
load:0x40078000,len:8160
load:0x40080400,len:5732
entry 0x4008069c
[E][vfs_api.cpp:64] open(): /littlefs/schedule.json does not exist
```

It complains something about :
open(): /littlefs/schedule.json does not exist

Can someone clarify to me how do I go about solving this issue? 

Perhaps there was some initial setup that I have missed ? I have just simply uploaded the program to my device and thats it

**Comment by jeremypoulter** [comment]
That file should be created if/when you use the timers so than error shouldn't stop the firmware from working.
