### ISSUE TITLE
Incorrect label for start/stop button when timer is set 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#185]
When an EV is connected the charging timer is scheduled for a later time the manual override 'start' button is incorrectly labelled 'stop'. Clicking this 'stop' button then starts the charge by activating a manual override. 

![OpenEVSE](https://user-images.githubusercontent.com/758844/117226185-03b58380-ae0c-11eb-95b4-5bbe80dc5ec1.gif)

![Screenshot 2021-05-06 01 36 35](https://user-images.githubusercontent.com/758844/117225982-8558e180-ae0b-11eb-9b27-1dab29dbede1.png)

**Comment by jeremypoulter** [comment]
Fixed in https://github.com/OpenEVSE/openevse_wifi_gui/commit/74011b2a20543414bdeb4df439bb5b9939f37c02
