### ISSUE TITLE
V4.0.1 Olimex ESP32 Gateway Not responding OpenEVSE firmware 7.1.3

### ISSUE THREAD

**Issue by wjhrdy** [OpenEVSE/ESP32_WiFi_V4.x#186]
V4.0.0 seems to be working but when I upgrade my ESP32 to V4.0.1 it doesn't seem to be connecting to the OpenEVSE Board, luckily I can downgrade back to 4.0.0 and it still works.

OpenEVSE Not responding or not connected

![CleanShot 2021-05-07 at 14 20 07](https://user-images.githubusercontent.com/1795778/117492573-4dfc4900-af61-11eb-864a-91d356401040.png)

![CleanShot 2021-05-07 at 14 19 02](https://user-images.githubusercontent.com/1795778/117492553-450b7780-af61-11eb-9021-bdc800ccf11d.png)

**Comment by glynhudson** [comment]
Apologies, there was an issue with the 4.0.1 release for the es32 gateway, this has now been fixed. Please to update again using this file: https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/download/4.0.1/esp32-gateway-e.bin

Note: currently HTTP update via the web interface is not working for the ESP32 gateway. You will need to update using a micro USB connection and esptool https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/master/docs/wired-ethernet.md#uploading-pre-compiled

**Comment by wjhrdy** [comment]
This worked. Thanks.
