### ISSUE TITLE
HTTP update failes on ESP32 Etherent gateway 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#187]
Testing trying to update from 3.3.2 to 4.0.1 

![Selection_436](https://user-images.githubusercontent.com/758844/117549915-f16a5e00-b034-11eb-9aea-45c51a39b59b.jpg)
![Selection_435](https://user-images.githubusercontent.com/758844/117549916-f202f480-b034-11eb-9141-34f5def2c62e.jpg)

**Comment by FatJuan** [comment]
Just upgraded to 4.0.1 from 3.3.1 using openevse_huzzah32.bin had same issue but resolved itself when tried 2nd time all up to date now. Thanks all!

**Comment by glynhudson** [comment]
Interesting, are you using an esp32 Ethernet gateway? Probably not since you mention you are using `openevse_huzzah32.bin`. This issue is referring specially the esp32 Ethernet gateway. HTTP update should be working fine on the Huzzah and OpenEVSE Wi-Fi module.

**Comment by FatJuan** [comment]
Sorry misread the header. Yes not using Ethernet gateway.

**Comment by jeremypoulter** [comment]
Just been having a look at this, I think the issue is that with the wired connection the update is being delivered to fast and we are never going round the main loop and the watch dog is kicking in and rebooting. Over WiFi the update looks to be working for me.

**Comment by jeremypoulter** [comment]
I think this may need some updates to the Mongoose library, we are currently using v6 but there is v7 now. It may be wise to update but this might be a large amount of work...
