### ISSUE TITLE
Add label on web interface to indicate which WiFi module is installed 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#188]
We now have a number of different ESP32 WiFi modules in circulation e.g Huzzah, OpenEVSE WiFi V1 and ESP32-etherent-gateway. This makes selecting the correct FW update confusing for the user and remote debugging can be tricky. 

It would be useful to display the platformio build environment name on the WiFi interface under the System > WiFi FW

**Comment by jeremypoulter** [comment]
This duplicates #49
