### ISSUE TITLE
Cannot take over push button via MQTT

### ISSUE THREAD

**Issue by basak** [OpenEVSE/ESP32_WiFi_V4.x#190]
Thank you for OpenEVSE!

I'd like for the Wifi module to ignore the push button, and instead publish button pushes to MQTT so that my home automation controller can make use of it.

This is sort of related to #112. If that were implemented, then I could use it to have the Wifi module ignore button pushes, and independently it could always send MQTT messages on button pushes regardless of any other setting.

**Comment by glynhudson** [comment]
This is certainly a niche use case, but I see no reason why it can't be implemented at the same time as #112. Push button could be disabled but events still published to MQTT 👍
