### ISSUE TITLE
V4.0: Solar PV divert (EcoMode) does not function when charging timer is set

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#192]
When running V4.0.x when a charging timer is set solar PV divert (eco mode) does not function even if there is available solar / grid export. 

Previously when running V3.x when Eco mode was active the EVSE would charge from solar during the day when there was excess generation then 'topup' the EV at full power charging at night when the charging timer became active. IMO this functionality should be restored. 

User feedback: https://community.openenergymonitor.org/t/eco-pv-divert-not-working-after-upgrade-to-v4/17780/5?u=glyn.hudson

**Comment by js1tr3** [comment]
Looks like maybe I got bit by this one also, but I didn't have any timer set.
![Screenshot_20210617-121119_Samsung Internet](https://user-images.githubusercontent.com/633873/122475403-9c562c00-cf92-11eb-9ca7-53b74f1da491.jpg)
