### ISSUE TITLE
Log Solar PV divert MQTT data to Emoncms

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#196]
In order to help with debugging, it would be very useful if the OpenEVSE could log the MQTT data being received for Solar PV Gen / Grid IE to Emoncms along with the calculated current value. Solar PV divert operation seems to cause a lot of confusing, it's very hard to debug without data being recorded and graphed since screenshots of the interface don't always show the full picture since the data is filtered.

**Comment by js1tr3** [comment]
like this?
![image](https://user-images.githubusercontent.com/633873/121421190-e3617300-c93b-11eb-804b-430afcaa37b3.png)

**Comment by jeremypoulter** [comment]
Thanks, I thought I had done it just hadn't got round to checking ;-) @glynhudson everything that updates in realtime on the UI is also exposed over MQTT

**Comment by glynhudson** [comment]
Mm I'm running latest 4.0.1 and posting to emoncms.org with solar divert enabled and I don't see many of the Inputs you have. What version are you running? 

![Screenshot 2021-06-10 00 47 10](https://user-images.githubusercontent.com/758844/121443508-84c0e700-c985-11eb-88f3-a5c99a0e9044.png)

**Comment by js1tr3** [comment]
I'm running 4.0.1, but I have my own emoncms server running at home with the latest version from git.

**Comment by jeremypoulter** [comment]
Ah right it is only goes to MQTT, not EmonCMS, can probably make it do both, but is more event driven so didn't send to EmonCMS initially to avoid sending too many messages

**Comment by glynhudson** [comment]
Ah right, that's the issue. If we could post all the metrics to emoncms that would be ace, most users use the Emoncms service to log the data to Emoncms rather than MQTT
