### ISSUE TITLE
Locale settings for numbers are not correctly interpreted on input and Wifi module reboots

### ISSUE THREAD

**Issue by treepleks** [OpenEVSE/ESP32_WiFi_V4.x#200]
I'm living in France and we use a comma ',' instead of a decimal point '.' to separate the integer from the fractional part in numbers.

The Web interface (javascript) knows this somehow since it displays floating-point numbers with a"," in the fields that can be user-modified (and only those). For example, in the Services/Solar PV divert/Divert smoothing attack field, I can see "0,4" (not "0.4"). This makes the interface a bit inconsistent since all floating-point numbers are printed with a decimal point and only those that can be modified are using a comma.

Of course, this invites the user that wants to modify this field to also use a comma. But if you do this and hit the "save" button at the bottom, the web interface says, after some time that the config could not be saved, and the wifi module reboots. If instead, you use a decimal point, things go smoothly.

My understanding is that numbers are correctly "localized" when they are printed on the web interface but not when they are read (input).

My own preference would be to either use decimal point everywhere or to use a localized version everywhere and more importantly to accept input formatted as the number is printed.

**Comment by jeremypoulter** [comment]
I assume that is the browser trying to be helpful, some of the input fields are defined as numbers so the browser is probably applying some localisation. I think for us to properly support localisation it would be best to rebuild the UI from the ground up using a proper framework and tools.
