### ISSUE TITLE
Failure to connect to AP when poor signal

### ISSUE THREAD

**Issue by julianwb** [OpenEVSE/ESP32_WiFi_V4.x#205]
It seesm that this is a known problem with ESP-IDF and WiFi.
Symptoms: frequently attempts to connect to AP result in STA_START, STA_DISCONNECTED, AUTH_FAIL.   At the third attempt the code reverts to AP mode; behaviour I find to be somewhat obscure, as the button is still available for such a choice.
Resetting the WiFi 
>      WiFi.persistent(false);
>      WiFi.disconnect();
>      WiFi.mode(WIFI_OFF);
>      WiFi.mode(WIFI_STA);
and re-attempting the connection succeeds.

ref: <https://github.com/espressif/arduino-esp32/issues/2501>

**Comment by chris1howell** [comment]
95%+ of OpenEVSE based stations do not have an external button, the button is optional and presents a significant security concern for publicly accessible stations. Not only can settings be changed but the WiFi control could be hijacked onto another network especially if the password is not set or discovered via bruteforce.

The automatic starting of AP mode is vital for users that incorrectly enter their password during initial configuration or take their station on the road.

I think it would be fine to try a few more times and wait a little longer between atempts especially if the change included the information on the display for each atempt and starting of AP mode.
