### ISSUE TITLE
Station Serial Number

### ISSUE THREAD

**Issue by chris1howell** [OpenEVSE/ESP32_WiFi_V4.x#218]
Devoloper Mode should allow a set once (If null) feature to assign the station, port and meter serial numbers. Wiping would require full FLASH/EEPROM erase.

This serial number should be avaliable in the HTTP configuration info, MQTT announce and sent via OCPP.

**Comment by jeremypoulter** [comment]
Is this something that should go into the OpenEVSE flash?

**Comment by jeremypoulter** [comment]
@chris1howell Can you comment on if these should be in the OpenEVSE flash? Maybe just the meter serial number? but can you also clarify what the difference between each of these is?

Realistically how secure do these values need to be? Is just writing to the flash and blocking in software sufficient? or do we been to depend on hardware features to protect from changes, eg use the eFUSE on the ESP32?

**Comment by glynhudson** [comment]
Can the ESP serial number be used for this? I guess this could cause issues if the WiFi module was changed / upgraded?

**Comment by chris1howell** [comment]
The connector serial number should be the controller, same with the power
meter unless another external power meter is used. The chassis serial
number can be stored wherever we choose.

**Comment by jeremypoulter** [comment]
I think in our context the meter is the OpenEVSE and also in the future we should have multiple OpenEVSE per WiFi module, so I would propose the following:

- ESP32 unique ID for the controller/station serial, can't be set
- Unique ID from the ATMEGA382 (https://www.thethingsnetwork.org/forum/t/arduino-has-a-unique-id/21415/4) for the meter id
- one user programmable id stored in (ESP32) flash for the port? Although again with multiple EVSEs would there logically be multiple? @chris1howell you also mentioned chassis number is this the same?

Is this acceptable?

**Comment by jeremypoulter** [comment]
https://gist.github.com/speters/f889faec42b510052a6ab4be437d38ca

**Comment by jeremypoulter** [comment]
https://github.com/ricaun/ArduinoUniqueID
