### ISSUE TITLE
Add SoC and range limits

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#225]
Now SoC integration is implemented it, SoC limit feature can now be implemented. The easiest way is probably a dropdown box under the energy limit with a few presets e.g 60%, 70%, 80%, 90%

**Comment by kallisti5** [comment]
this would be nice... especially as a Bolt EV owner ;-) 
Tired of hopping into the car to tune the charge limit.

**Comment by chris1howell** [comment]
Additionally a limit should be added for distance miles/km. Example... Charge to 300km range.

**Comment by pdhoogh** [comment]
@chris1howell : as range is from GOM (_Guess_-O-Meter), the charge too will be a guess. Depends totally on load, weather, style... results from the past do not guarantee similar results in future etc... so, what are you precisely looking for?

**Comment by KipK** [comment]
My 2 cents on this one. New Limit engine now handles time, energy, soc, and range.

**Comment by KipK** [comment]
Also added System Limits , persistant ones defined from config. 
UI is all done, please give me your feedback on the UX.  Enjoy :)
