### ISSUE TITLE
Reset whole EVSE by C++ API call

### ISSUE THREAD

**Issue by matth-x** [OpenEVSE/ESP32_WiFi_V4.x#228]
The OCPP specification demands a complete reset procedure for the whole EVSE. Jeremy already told me that this is already possible via RAPI call but should better be implemented via C++ API call. For the ESP32 itself, it's no problem to use `ESPAL.reset()`.

**Comment by jeremypoulter** [comment]
C++ API for restarting the EVSE module implemented via #618

**Comment by jeremypoulter** [comment]
@matth-x Do you want to use this ticket to implement the OCPP bit when merged or is there another ticket for that?

**Comment by matth-x** [comment]
@jeremypoulter I'm planning a cumulative update which will also address the new reset function. Since the requested feature is done, I'm closing this ticket, thanks.
