### ISSUE TITLE
OCPP - unlock connector via command

### ISSUE THREAD

**Issue by matth-x** [OpenEVSE/ESP32_WiFi_V4.x#230]
In case the locking actuator of the plug fails, the CPO should be able to use the OCPP command `UnlockConnector` to trigger the EVSE to retry unlocking the connector. It is okay for the moment to reply with a `NotImplemented` message if the EVSE doesn't support it, but it would be really helpful to allow a more extensive remote management via OCPP.

**Comment by jeremypoulter** [comment]
This would need some support from the OpenEVSE firmware, we started a discussion in https://github.com/lincomatic/open_evse/issues/141 but there was no conclusion. @chris1howell / @glynhudson  any thoughts?

**Comment by lincomatic** [comment]
Hmm.. seems we need a RAPI lock/unlock command for Mennekes? If we do that, then I agree, we should just leave it to WiFi to control it. But if we're doing that, it really seems more logical to just take the EVSE out of the equation completely and connect the lock motor to the WiFi.
For non-Mennekes scenarios, the AUTH_LOCK code alone can handle the access control of charging

**Comment by pavel167** [comment]
Hello,
Can someone suggest how unlock feature could realised on a charger, i.e. upon reception of "unlock connector" command over OCPP (from back-end), the charger should send some "unlock" command to connector over CAN bus ... something like this ?

**Comment by chris1howell** [comment]
@pavel167

In Europe, it is common to bring your own cable, the cable has a connector
on both ends. The station locks the connector to the station when the
charge starts. Once the vehicle end is unlocked and unplugged the station
unlocks the station side connector.

OCPP connector unlock allows a command to unlock the station side connector.

**Comment by jeremypoulter** [comment]
@matth-x this is now implemented in the OpenEVSE firmware, #289 covers adding the generic handling in the WiFi firmware
