### ISSUE TITLE
Eco PV Divert doesn't work

### ISSUE THREAD

**Issue by cris88** [OpenEVSE/ESP32_WiFi_V4.x#235]
Hello,

I have a problem with PV Divert. Basically it does not regulate as it would be supposed. It is always charged at the maximum amperage set. Grid import and export values ​​are correctly shown on the portal. There are some attached print screens. Thanks.
![Screenshot_20210822-124521_Chrome](https://user-images.githubusercontent.com/1536899/130354393-e758070e-9414-4280-8a50-db252786d473.jpg)
![Screenshot_20210822-124841_Chrome](https://user-images.githubusercontent.com/1536899/130354394-b9ec8924-ac50-4023-b15d-a83a6e4173e1.jpg)

**Comment by glynhudson** [comment]
Your config looks correct, please ensure your Grid IE power readings are positive import and negative export. It's also important that the Grid IE feed includes the power consumed by the EVSE. The Grid IE emonPi CT sensor should be clipped around the incoming cable right as it enters the property before any loads. 

Please update to the latest WiFi FW version V4.1.0: https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/tag/4.1.0

**Comment by cris88** [comment]
hello @glynhudson. Yes Grid IE is in watts, and positive is the value that im importing from grid, when negative the value that im exporting to the grid. Ok i will do the update and give feedback

**Comment by doppiaemme** [comment]
> hello @glynhudson. Yes Grid IE is in watts, and positive is the value that im importing from grid, when negative the value that im exporting to the grid. Ok i will do the update and give feedback

I had the VERY same issues with 4.0 which seem disappeared (for now) thankfully to the upgrade to 4.1.0. 
the latter seems so much more stable
