### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP32_WiFi_V4.x#244]
We could to with better logging for diagnosis of in field issues, the current MicroDebug library is only really useful for debugging, we need some other levels of debug that can be left on in production builds.

- selection of log messages
  - debug
  - info
  - warning
  - error
- debug level compiled out by default enabled per module
- output to serial and web
- optional runtime config of levels
- optional colour highlighting

**Comment by glynhudson** [comment]
I agree, this would be useful
