### ISSUE TITLE
Manual override over mqtt

### ISSUE THREAD

**Issue by ayasystems** [OpenEVSE/ESP32_WiFi_V4.x#250]
Hi,

Manual override is published by mqtt but it is not changable over mqtt. 

The only way to release manual override seems be make a post delete ( handleOverrideDelete )

Could be managed over mqtt in the next release?

Best regards!

**Comment by Tifaifai** [comment]
Hi,
Why don't use RAPI command via MQTT : <base-topic>/rapi/$FS ?

**Comment by ayasystems** [comment]
I don't know about this feature, I will test it. Thanks a lot

**Comment by jeremypoulter** [comment]
Just be aware that the v4 firmware doesn't handle RAPI commands being sent by other sources and this will likely be disabled at some point.

**Comment by jeremypoulter** [comment]
MQTT API will be added via #358
