### ISSUE TITLE
"Button Pressed *** Factory Reset ***" boot loop on nodemcu-32s

### ISSUE THREAD

**Issue by DrFrankReade** [OpenEVSE/ESP32_WiFi_V4.x#254]
Running on a classic nodemcu-32s board, **Wifi V4.1.0** with external level shifters to OpenEVSE on **V7.1.3 firmware**

I keep getting a boot loop when env is set to nodemcu-32s which seems different than the panic reboot that others are seeing.  It keeps thinking the button is pressed.

- BUTTON PRESSED
- *** FACTORY RESET ***

and so on. 

Added
` -DWIFI_BUTTON=0
  -DWIFI_BUTTON_PRESSED_STATE=LOW`
with button state both high and low, and no dice.
The external button DOES work as tested in the Arduino IDE as expected.
Suspect that this is perhaps a pin definition issue? But why would it also reboot when I set
 `-DWIFI_BUTTON_PRESSED_STATE=HIGH` also? No matter WHAT pin it was on?

I got it working by setting `default_envs = openevse_huzzah32`, and switching the debug and rapi ports ` -D RAPI_PORT=Serial2
  -D DEBUG_PORT=Serial`, and commenting out `# SERIAL_RX_PULLUP_PIN=3`  in `[env:openevse_huzzah32]`. Seems fine now.

What weirdness is going on?  This ESP has been running for years, and with this hack it's back running. 

Thoughts?

**Comment by jeremypoulter** [comment]
Had a look at this and the issue was the LED setting, corrected this in #275
