### ISSUE TITLE
Support upgrade directly from GitHub

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP32_WiFi_V4.x#259]
In the UI download the latest release info (<https://api.github.com/repos/OpenEVSE/ESP32_WiFi_V4.x/releases/latest>) and then use the new HTTP client upgrade (#258) to download/upgrade from the release assets.

This will probably need support for upgrading from a Zip file and/or eventing the upgrade state.

**Comment by jeremypoulter** [comment]
With the merge of #266 the binaries are now uploaded to GitHub in a format we should be able to directly download on the WiFi module. I did some experiments on [jeremypoulter/issue259](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/tree/jeremypoulter/issue259) branch.

- The link that you get from the GitHub API redirects to the actual download location, so we need to support 302 redirects either in ArduinoMongoose or the app
- Looks to be an issue downloading the binary on the ESP32, ArduinoMongose looks to get the redirect message but not parse it as HTTP so just exits, works fine in the streaming example.

**Comment by jeremypoulter** [comment]
requires #502

**Comment by jeremypoulter** [comment]
Looking at doing this directly in the HTTP OTA module, should be possible, but looks like there could be bugs in Mongoose :(

**Comment by KipK** [comment]
works great 👍 For now on new UI it only propose to install the current stable. 
Does it has sense to propose nightlies ?

**Comment by jeremypoulter** [comment]
Probably, but a little harder to work out if there is a newer version
