### ISSUE TITLE
[BUG] Websocket data does not match documentation

### ISSUE THREAD

**Issue by firstof9** [OpenEVSE/ESP32_WiFi_V4.x#263]
In the documentation `wattsec` and `watthour` should update via the HTTP websocket, these fields are missing from the websocket updates.

**Comment by jeremypoulter** [comment]
Yeah I am updating the docs currently for v4 (#9) but the `wattsec` and `watthour` are terrible names so I have added `session_energy` and `total_energy` and that is both in the web socket, `/status` and MQTT:

![image](https://user-images.githubusercontent.com/6116992/141204308-9acd354f-d9db-49c9-9f4c-b212f7e29dae.png)

![image](https://user-images.githubusercontent.com/6116992/141204419-cbed4dd2-0e04-48f6-a94e-aedee74b1e2f.png)

![image](https://user-images.githubusercontent.com/6116992/141204783-580ee61e-af45-40df-82b0-6a580849fbb4.png)

**Comment by firstof9** [comment]
I assume these will be in the next firmware update then?

**Comment by jeremypoulter** [comment]
If not in 4.1 then yeah, you can try the [pre-release](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/tag/latest)

**Comment by ruimarinho** [comment]
Confirmed on 4.1.1.dev.

![image](https://user-images.githubusercontent.com/288709/147168187-af6f0a58-b401-40b2-973e-9f15f41a1835.png)
