### ISSUE TITLE
Display session energy as kW with one decimal place

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#264]
Currently, the session energy is displayed in Wh with two decimal places! The results in a rather large number, and when the session energy > 10kWh the LCD display is truncated and the 'h' symbol is missing, which results in confusion since it then looks like a power value rather than energy.

I propose display session energy as kW with one decimal place, what do you think @chris1howell ?

![PXL_20211103_193418481](https://user-images.githubusercontent.com/758844/140387295-e5f1ef10-9970-4ee0-b995-8c90d31195e3.jpg)

**Comment by chris1howell** [comment]
Yep, sounds good.

**Comment by jeremypoulter** [comment]
Been meaning to make this a bit more sane. I would propose a degree of scaling based on the size, ie Wh for > 4000, kWh > 4,000,000, etc and that would just be a generic thing across the board, ie total energy, current power, etc

**Comment by jeremypoulter** [comment]
Or given the LCD has a specific number of characters maybe just base on that and give the max precision for the available space

**Comment by glynhudson** [comment]
Nice work, this has fixed the issue perfectly :+1: 

![PXL_20211130_235743515-COLLAGE](https://user-images.githubusercontent.com/758844/144158114-02153c46-8371-4da7-aaf1-1207e43c6ef4.jpg)
