### ISSUE TITLE
Time to full (set) charge

### ISSUE THREAD

**Issue by andriuskr** [OpenEVSE/ESP32_WiFi_V4.x#268]
![140695020-a7636ba9-ca22-47ba-9cb9-e7a79808a082](https://user-images.githubusercontent.com/13429780/141132311-78c1a4e6-86d8-4d4a-b907-a65baf905730.png)
"Time to full charge" is not very accurate term if vehicle is set to charge battery to 90%. It could fetch this from tesla acc and show not "Time to full charge", but "Time to 90% charge" or "Time to 80% charge"

**Comment by glynhudson** [comment]
@jeremypoulter is the 'time to charge' metric already fetched from the Tesla API? This metric is currently not used for any purpose, I vote removing it to avoid confusing at the moment.

**Comment by jeremypoulter** [comment]
Initially we can probably just change it to 'time to complete' or something more generic, think it is just for information, but probably quite useful, especially on the LCD.
