### ISSUE TITLE
Vehicle SoC on display

### ISSUE THREAD

**Issue by andriuskr** [OpenEVSE/ESP32_WiFi_V4.x#269]
SoC of vehicle is not displayed on charger screen.

**Comment by jeremypoulter** [comment]
It is working for me, ![PXL_20211110_222221738.jpg](https://user-images.githubusercontent.com/6116992/141203516-81d1d629-58ca-4625-b7a8-003d4a542dd4.jpg)

Do you see the SoC in the web UI?

**Comment by glynhudson** [comment]
What FW version are you running? Have you configured the SoC source; either Tesla or MQTT? Is the SoC shown on the web page and the `/status` output?

**Comment by andriuskr** [comment]
Firmware is latest dev build. SoC source i have configured, it was working firs. Now it only shows fetchin vehicle data and nothing happens
