### ISSUE TITLE
Button disable not working

### ISSUE THREAD

**Issue by omriasta** [OpenEVSE/ESP32_WiFi_V4.x#270]
I have an openevse hardware version 4 with firmware 7.1.3. 
I used to have esp8266 wifi module with firmware 2.9.1.
Disabling the button with $FF B 0 worked when I had the 8266.
I just upgraded the wifi module to the latest hardware and running firmware v4.1.0 now this command is not working as it should. I do still get an "OK" response when sending the command but the button still works and puts the Openevse into manual override. Is there any way to disable the button completely so it can't be used to change the charging status?

**Comment by jeremypoulter** [comment]
This is because the 4.x firmware processes the button press on the WiFi module. There is an open issue #112 to add an option to disable the button.
