### ISSUE TITLE
Inconsistent energy reporting

### ISSUE THREAD

**Issue by Rolf-Pete** [OpenEVSE/ESP32_WiFi_V4.x#285]
Using the OpenEVSE Version "5.0.1 4.0.1" there is the folowing inconsistent behavior in the energy reporting:
During charging, the accumulated-energy does not change and the session-energy increments. Then the charging is stopped by Rapi-command. As soon as the vehicle is unplugged, the session-energy is added to the accumulated-energy but the session-energy is not reset to 0 at the same time. This reset to 0 is done only as soon, as the vehicle is replugged again.
This result in an inconsistent energy-value when - as it was before - the two energy-value are always added to get the actual overall value.

**Comment by glynhudson** [comment]
Energy reporting has now been overhauled and much improved in latest version in V2 UI
