### ISSUE TITLE
MQTT connection

### ISSUE THREAD

**Issue by FCampos1977** [OpenEVSE/ESP32_WiFi_V4.x#286]
MQTT loose connection sometimes a day ( board ESP32 Ethernet )

Connected to router via Ethernet

![image](https://user-images.githubusercontent.com/65458265/145113069-c597e342-7440-43c7-84c5-a52cbd9d3b91.png)

![image](https://user-images.githubusercontent.com/65458265/145113115-80d6f09e-0e58-423f-9c06-e8aa0f815b01.png)

![image](https://user-images.githubusercontent.com/65458265/145113163-40be9398-3402-4dc8-abb3-3255ebc66b59.png)

**Comment by ruimarinho** [comment]
I have the same issue but on WiFi. See https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/248 and https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/135.

**Comment by FCampos1977** [comment]
I don't know why, but WIFI module, ask router to an IP address 3 times a day.

Should have an option for static IP

**Comment by glynhudson** [comment]
This should be fixed in latest FW
