### ISSUE TITLE
Recommended pinout configuration for ESP32 DevKitC v4 ESP32-WROOM-32U

### ISSUE THREAD

**Issue by ruimarinho** [OpenEVSE/ESP32_WiFi_V4.x#291]
Hi @jeremypoulter,

Could you suggest a pinout configuration for platformio.ini for the ESP32 DevKitC v4 ESP32-WROOM-32U board ([Aliexpress](https://www.aliexpress.com/item/4000090521976.html?spm=a2g0s.9042311.0.0.7e214c4dEyDasb))?

I have the official Huzzah32 but I'm giving the IPEX board a try (ESP32-WROOM-32U) to see if the external antenna helps with my constant MQTT dropouts.

Thank you.

**Comment by jeremypoulter** [comment]
I think the same pinout as the NodeMCU-32S should work, with the default serial 1 pins connected to the OpenEVSE

**Comment by ruimarinho** [comment]
Thanks! Does this board require the configuration of any neopixel stuff?

**Comment by jeremypoulter** [comment]
No, no Neopixel stuff for that board

**Comment by ruimarinho** [comment]
Looking at the schematics, wouldn't this board be limited to one serial port (TXD0/RXD0), therefore `RAPI_PORT=Serial`? 
![image](https://user-images.githubusercontent.com/288709/146681958-3cc9da3a-daaf-43d8-b3d9-6b3ef2e5bd9e.png)

How do I figure out which pin controls the onboard LED? Sorry for the questions :)

**Comment by jeremypoulter** [comment]
Assuming it is this board: https://dl.espressif.com/dl/schematics/ESP32-Core-Board-V2_sch.pdf I think the on-board LED is directly linked to the power so can not be controlled. 

The `TXD0`/`RXD0` are connected to the USB serial so not really suitable for OpenEVSE comms so you need to use one of the other UARTs, these are not shown on the schematic, but if you look at a [pinout](https://www.theengineeringprojects.com/wp-content/uploads/2020/12/introduction-to-esp32-3.png) you will see there are additional UARTs on `GPIO9`/`GPIO10` and `GPIO16`/`GPIO17`, the latter (Serial2) is probably the best as `GPIO9`/`GPIO10` conflict with the internal flash. You can also configure the UARTs to any pins.

**Comment by ruimarinho** [comment]
@jeremypoulter got it, thanks! In that case (assuming `-D RAPI_PORT=Serial2`), should/could I do `-D DEBUG_PORT=Serial` to spy on messages? Although it seems like this is the default already.. https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/3e2859fc0b03c728e1b3d936a92152140539e52c/src/debug.cpp#L5

**Comment by jeremypoulter** [comment]
Correct, the default is to use `Serial` as the debug.

**Comment by ruimarinho** [comment]
Thanks! Everything is working now :) what would be the best way to simulate the `WIFI_BUTTON` on GPIO0? I have EN and Boot buttons, but those are hardwired for ESP32's reset and download function (which I don't really know what it means).

**Comment by jeremypoulter** [comment]
The boot button will be connected to `GPIO0` so should be ok to use as the `WIFI_BUTTON`

**Comment by wrightwells** [comment]
I’ve connected an ESP32 WROOM 32U for the external antenna and complied using the huzzah32_dev env.
It connects to the EVSE board and all commands work but when powered from the 5v outlet of the EVSE board, the ESVE RGB display goes DIM and pluses. When the WIFI board is not connected or powered seperately the RGB display is very bright and readable?
As the openevse Wi-Fi board uses the 12v pin is this expected?

**Comment by jeremypoulter** [comment]
The 5v line on the OpenEVSE module can not supply sufficient power for the ESP32, you have to take the 12v and use a buck converter to drop the voltage down to 5v

**Comment by wrightwells** [comment]
Thanks , buck installed and I up and running.

**Comment by ruimarinho** [comment]
In my case, I've used the `openevse_nodemcu-32s` environment and it's working great. 

```
pio run  -e openevse_nodemcu-32s -t upload
```

<img width="431" alt="Screenshot 2022-01-14 at 10 59 07" src="https://user-images.githubusercontent.com/288709/149668551-672e112a-4dfd-440a-813e-b856054220fb.png">
