### ISSUE TITLE
LCD: Bad sequence statuts display

### ISSUE THREAD

**Issue by Tifaifai** [OpenEVSE/ESP32_WiFi_V4.x#295]
Hi,
On my OpenEVSE, Configuration : Firmware 7.1.3 + Wifi 4.1.1 (Hardware OpenEVSE Wifi v1).

On the LCD, The second line is ok with informations cycle (energy, etc.)
The first line display bad status sequence.

Sequence:
  Restart Firmware
  Ready - Green Led - No vehicle connected
  Charging - Blue Led - Vehicle connected - Charge
  Connected - yellow Led - Vehicle connected - No Charge
==> Bug:  Connected - Green Led - No vehicle connected

I must restart firmware but identiccaly sequence
  
Thank you for your great job

**Comment by jeremypoulter** [comment]
Have been able to replicate this, will take a look.

**Comment by Tifaifai** [comment]
Use case sequence #2: 
Restart Firmware
Ready - Green Led - No vehicle connected
Push 'Pause' Charge option
L0: zzz Sleepling zzz / L1: Manage override - Purple Led
Push 'Clear' Charge option
=> Bug: L0: zzz Sleeping zzz - Green Led

**Comment by Tifaifai** [comment]
if you generate a 4.1.2 release, I want well to test this. (link to download ?)

**Comment by jeremypoulter** [comment]
You can grab the assets from the PR build, https://github.com/OpenEVSE/ESP32_WiFi_V4.x/actions/runs/1670141244

**Comment by Tifaifai** [comment]
I just finished testing and the PR #298 is perfect! looking forward to the release 4.2 !
