### ISSUE TITLE
Pause button broken

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP32_WiFi_V4.x#307]
As reported in #296 

> However, the 'pause' button seems to be broken. When I click pause, nothing happens and the error home.js:1 Uncaught TypeError: o.openevse.isPaused is not a function is displayed in the console.
> 
> ![Screenshot 2022-01-29 00 37 21](https://user-images.githubusercontent.com/758844/151639566-e7cf7c2a-7f1f-4083-b454-30242431cc25.png)

**Comment by glynhudson** [comment]
Mm I seem to still be having the same behaviour testing with the fix PR. I've cleared the cache and tested in private browsing mode. 

![Screenshot 2022-02-01 01 58 18](https://user-images.githubusercontent.com/758844/151903491-e91b1d4e-024e-4975-960a-665f838f7e32.png)

**Comment by jeremypoulter** [comment]
Needed the GUI changes merging, forgot to create a PR, should be fixed not

**Comment by glynhudson** [comment]
Ok, no worries. I see the GUI PR is now merged: https://github.com/OpenEVSE/openevse_wifi_gui/commit/6c52c6b967b4f9104f7a57838f4385d460b34bff

Should I test again? Will I need to compile locally to pull in the new GUI? 

Is it possible to test a PR without merging using github actions artefacts? Or do PRs need to be merged and compiled locally?

**Comment by jeremypoulter** [comment]
The builds are all done as part of the 'Checks', see https://github.com/OpenEVSE/ESP32_WiFi_V4.x/actions/runs/1770122468, I guess it is a little hidden if they pass but look for the green tick against the last commit or the checks section at the bottom.
