### ISSUE TITLE
PV divert problems ONLY when PV ratio is less than 1

### ISSUE THREAD

**Issue by danpadure** [OpenEVSE/ESP32_WiFi_V4.x#312]
I think I found a reason for strange PV divert behaviour.
So I think these issues only occur when the available diverted PV power is LESS than 6A. And ONLY when you start the charging without enough PV power, so it has to wait for the sun
I think there's something wrong in the code for when power is under 6A

Here is a graph showing the issue 
![image](https://user-images.githubusercontent.com/48951409/153391288-c0339376-e8d1-4eec-8117-23e3af777b56.png)

Another more detailed graph
GREEN= total PV OUTPUT
BLUE=grid import/export (negative is export)
RED=OpenEVSE Current (A)

![image](https://user-images.githubusercontent.com/48951409/153407291-485f6a68-dd18-404e-9056-7099ec778642.png)

OpenEVSE started charging when export was -300W as it's coifigured to start at 0.2 PV power ratio.
But started at max current (16A).
It operated at that speed until the PV power ratio was 1.
Then after that it operated normally, increasing the current as the panels produced more and more power
I also remember that during the autum when I had configured to start at 1 ratio I had no such issues

**Comment by pdhoogh** [comment]
I have seen similar behavior, but it is not predictable. With "_Required PV power ratio_" < 1.0, I have seen the desired behavior when there was more than 6A available first and the PV power dropped below 6A, the current stayed at 6A until minimum ratio was crossed and then charge stopped. Perfect.

But indeed if power is building up from below minimum ratio times 6A and crosses that ratio, the EVSE initiates charge and goes to Max Current.

The way I would think this should work - that is just me - is that when there is less than 6A available, the EVSE would still allow charging at 6A up to the point where the available current is (Required PV power ratio) times 6A. Do I understand this right?

**Comment by glynhudson** [comment]
I've also seen this behaviour in recent build 

![Screenshot 2023-03-31 01 38 18](https://user-images.githubusercontent.com/758844/228994534-b084b00e-4def-42ed-9a75-05ec264682a9.png)

**Comment by danpadure** [comment]
I think that if I set minimum ratio higher than 0.3, then the problem does not occur
