### ISSUE TITLE
UL issue - WiFi LED

### ISSUE THREAD

**Issue by chris1howell** [OpenEVSE/ESP32_WiFi_V4.x#317]
When a station is configured without an LCD Display, station state is not indicated when the station is in standalone mode. Once the station is joined to a WiFi network the LEDs correctly indicate state.

Proposed solution: keep the first LED1 as is, indicating WiFi status. LED2 and higher (if installed) should always be colored to indicate station state regardless of WiFi configuration. LED1 - WiFi State, LED2+ - Station State.

Note-Station under test had no display. WiFi has 5 LEDs 2 onboard OpenEVSE_WiFi_v1 and 3 additional connected to the LED expansion port.

**Comment by chris1howell** [comment]
Pixels added via the expansion port no longer show the station status. The onboard pixels LED 1 and 2 work correctly.

**Comment by jeremypoulter** [comment]
@chris1howell this works for me, are you sure you have `NEO_PIXEL_LENGTH` set correctly?

**Comment by jeremypoulter** [comment]
Tested on OpwnEVSE WiFi board as well for me

**Comment by chris1howell** [comment]
I am not sure this is resolved. I added 3 additional LEDs to the OpenEVSE
WiFi board and changed the number of LEDs in platform.ini.

LEDs 1 and 2 on WiFi work great but LEDs 3, 4 and 5 on the external board
are dark. All 5 work perfectly with a demo sketch that fades through each
color.

**Comment by jeremypoulter** [comment]
Which build l/version are you using? I will double check but looked to work fine with the off the shelf openevse_wifi_v1

**Comment by chris1howell** [comment]
Just tried the latest Development build... All is good.
