### ISSUE TITLE
Git actions automated build warnings

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#324]
The builds seem to be completing successfully, however there are a number of warning messages e.g.

![2022-03-03_18-23](https://user-images.githubusercontent.com/758844/156628225-527ca89f-94c6-4dd5-9b58-fdba6a186715.png)

https://github.com/OpenEVSE/ESP32_WiFi_V4.x/actions/runs/1912947458#artifacts

**Comment by jeremypoulter** [comment]
I think most of these are generated by the libraries/ESP32 core, need to find a way to filter all these out
