### ISSUE TITLE
HTTP update not working on ESP Gateway Ethernet

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#327]
I'm not sure if there is another issue for this, but HTTP firmware update has never worked on the ESP gateway module. Would it be possible to investigate if this could be relatively easily fixed? Of if there is an inherent issue with the ESP gateway which is not conducive to HTTP update? This is becoming more of an issue since many more users are now choosing Ethernet connectivity option.

**Comment by jeremypoulter** [comment]
Is an existing issue, #187
