### ISSUE TITLE
Teslamate/MQTT Time to full charge

### ISSUE THREAD

**Issue by VasDeferens** [OpenEVSE/ESP32_WiFi_V4.x#334]
Using Teslamate and it's MQTT integration I have setup my OpenEVSE to display vehicle data but the Time to Full Charge isn't correct. Teslamate pushes this data as a decimal. Using Tesla API it appears correct but as I use the OpenEVSE to charge another brand of EV in the future I would prefer to reduce waking the Tesla when not needed. Any ideas on how to resolve?

**Comment by jeremypoulter** [comment]
The value received over MQTT should be the seconds remaining, is it a different scale?

**Comment by VasDeferens** [comment]
Looks like Teslamate reports 2 hours as 2.00

**Comment by VasDeferens** [comment]
update: If I use the Tesla API the range is displayed in miles only. Might need a switch to allow kms...
