### ISSUE TITLE
FR: link to GitHub in the web ui

### ISSUE THREAD

**Issue by mikebaz** [OpenEVSE/ESP32_WiFi_V4.x#342]
Would it be possible to have a link in the web UI (the Advanced view, under Hardware, in the OpenEVSE WiFi section feels logical to me but I'll pulling that out of my backside) to the Releases page on GitHub?   the hardware info being shown there is a big help with making sure I don't accidentally flash the wrong firmware (*) so this feels like a reasonable next step?

Ideally I'd actually like an update notification by having the web UI look at the GitHub releases feed, but I realize that's a relatively large and somewhat unreasonable request, so I'm keeping my feature request small. 😊

(*) I made this mistake once before the new hardware info was added.  now I have a lovely programming cable. 🤣

**Comment by jeremypoulter** [comment]
This will be covered by #259, and that can be worked on fairly soon, I am updating the networking libraries which is the thing that was blocking it.
