### ISSUE TITLE
"Awaiting solar" status confusing

### ISSUE THREAD

**Issue by lebsd** [OpenEVSE/ESP32_WiFi_V4.x#346]
Unit set to PV Divert. Main windows Status shows "EV connected", "waiting for solar" (but with available current on the solar (>6A)).  At 1st I thought there was something wrong with the unit starting from the solar, so I reset the WIFI, no changes. Since I have a sensor  that monitors the grid power which feeds via node red the grid power, I checked it to ensure grid indicated power was correct and not stuck, reset my node red, no changes. Lastly, I checked the charge level on the car, it was indicating it was fully charged, explains the "EV connected" but not charging.   

The "waiting for solar" is in a sense misleading:  it required some troubleshooting but the reason is the car is fully charged.  My recommendation is logic that says "if the car is connected and the solar amps > 6 Amps, then display status "ready to charge" (vs "awaiting solar"). Awaiting for solar for me means that there is not enough solar power to turn on charging.  

![image](https://user-images.githubusercontent.com/55412823/165618205-0fdd35a6-1f0d-4bc5-a6ae-e0b62d967498.png)

**Comment by jeremypoulter** [comment]
Potential this may have been fixed by #431 will have to be tested.
