### ISSUE TITLE
MQTT "amp" message not updated to zero when solar charge stops?

### ISSUE THREAD

**Issue by tschiex** [OpenEVSE/ESP32_WiFi_V4.x#351]
When OpenEVSE is in Solar divert mode and starts charging, the MQTT "amp" topic is updated regularly with the charging current. When the sun goes down, a zero "amp" topic messgae is never sent and my MQTT board continues to display the last charging current for hours.

It would be nice to send a zero "amp"topic MQTT message when solar charges finishes.

**Comment by KipK** [comment]
I don't see this issue here.
"amp" is supposed to display the OpenEVSE current sensor. It should be updated whenever the divertmode is enabled or not each 30 sec at least.
