### ISSUE TITLE
Divert mode manual override and minimum charge time

### ISSUE THREAD

**Issue by ncaunt** [OpenEVSE/ESP32_WiFi_V4.x#361]
I noticed some behaviour that I did not expect around what seems to be the minimum charge time when using divert mode.

When there was sufficient PV output my EV started charging as usual in divert mode but the clouds returned promptly so I paused charging in the web GUI. Since this left the system in a state of manual override I opted to clear it, expecting charging would recommence when there was sufficient PV again. However charging started immediately and I think this is because insufficient time had passed since charging commenced. I was able to clear the override without charging starting again after this timeout had elapsed.

Should that minimum period be cleared when a manual intervention is made in divert mode?

**Comment by jeremypoulter** [comment]
That is a tricky one, currently all the different modes/controls (by design) operate independently of each other but maybe there is an argument to be made that setting/clearing the manual override (or anything else with higher priority) should reset the internal state of the drivet
