### ISSUE TITLE
Hide RFID config if no RFID hardware is connected

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#377]
Ideally the RFID config should be hidden or a message displayed e.g "no RFID hardware connected" if a compatible RFID reader is not detected.

**Comment by jeremypoulter** [comment]
@matth-x are you able to take a look at this?

**Comment by Tifaifai** [comment]
Hi,
Maybe add a RFID.md file to explain the mechanism and propose a hardware compatible ? 
Link to PN532 reader ?
THX

**Comment by glynhudson** [comment]
V2 UI has RFID config disabled if no RFID hardware is connected
