### ISSUE TITLE
Initial landing page Configuration Wizard

### ISSUE THREAD

**Issue by chris1howell** [OpenEVSE/ESP32_WiFi_V4.x#380]
With new regulations in the UK and configuration page for installer (full interface locked out), the initial landing page needs to allow additional options.

Enable/Disable default start/stop timer.
Upgrade firmware

**Comment by jeremypoulter** [comment]
I think this needs more of a wizard style setup than the current page. So should probably look at what should be on each screen.

**Comment by jeremypoulter** [comment]
Added the required bits to the UI, will change to a wizard as part of #401
