### ISSUE TITLE
The delay timer does not work

### ISSUE THREAD

**Issue by DmitryAVR** [OpenEVSE/ESP32_WiFi_V4.x#386]
Hello. I built OpenEVSE without a display. And the delay timer does not work for me (in the screenshot). 

![image](https://user-images.githubusercontent.com/106111146/177169576-7b0e82bf-ee3b-4ab3-960e-ea72fc4ad170.png)

When the timer is set, EVSE goes into standby mode. But charging does not start at the beginning of time. Is it due to the display not connected, or do I have another error?

**Comment by jeremypoulter** [comment]
Are you using any other 'smart' features, like PV divert?

**Comment by jeremypoulter** [comment]
Interesting have you previously set the time via NTP and set a time zone?

**Comment by DmitryAVR** [comment]
For example. Set the timer as in the screenshot. Charging on pause. Time zone: Etc/Universal
![image](https://user-images.githubusercontent.com/106111146/181201998-c90c0c95-5877-4188-87ce-5c3ae8859115.png)

Next, I set the timer to start 3 hours earlier and the charging was activated.
![image](https://user-images.githubusercontent.com/106111146/181202208-223155aa-27b2-497c-b998-0d7f11c693a6.png)
