### ISSUE TITLE
After adjusting current capacity via RAPI, `Pilot` reported doesn't follow.

### ISSUE THREAD

**Issue by linuxkidd** [OpenEVSE/ESP32_WiFi_V4.x#389]
- I use the RAPI command `$SC` over MQTT `openevse/rapi/in/$SC` to set charge current capacity to match leftover current on a shared 50 amp plug.
- Historically, the `Pilot` reported via MQTT, `/status` api, and the web interface would follow the value set using `$SC`. 
- In the past few releases, this has not been the case, and the `Pilot` value reported on all interfaces remains at whatever the latest Web UI set value.

Note: The new value is confirmed with the `$OK ##^##` response as expected, and the attached vehicle reports the new limit, so it is being applied, just not reflected in the reported `Pilot` value

```
> $SC 27
< $OK 27^05
> $GC 27
< $OK 6 80 27 27^1E
```
From `/status`
```
... "pilot":40, ...
```
And, the webUI:
![image](https://user-images.githubusercontent.com/6115364/178355980-b89b9eb9-bf12-4cf6-a5f3-954b37e9c271.png)

**Comment by jeremypoulter** [comment]
RAPI shouldn't be used anymore and will be disable in a future release, please use the HTTP `/claim` API
