### ISSUE TITLE
Relay Sticking, live power disconnection

### ISSUE THREAD

**Issue by kallisti5** [OpenEVSE/ESP32_WiFi_V4.x#390]
Hm, still dealing with relay sticking over time.  220v Level 2.  50A "advanced" relay.

* OpenEVSE Wifi 4.1.3 / openevse_wifi_v1
* OpenEVSE D7.1.3 / OpenEVSE v5

Physical Issues:

* Total Energy Delivered: 2067.04 kWh
* Relay terminals hazy and worn.
* Bit of brown haze on top terminal, likely arc flash smoke.
* I sanded and cleaned them once before ~ 6 months ago which solved the sticking issue for a while.

Things i've checked:

* Wiring is correct in unit.
* Vehicle is 2019 Chevy Bolt EV

**Comment by kallisti5** [comment]
It should be noted that the stuck relay doesn't happen when hand-disconnecting.  It's happening "when the car finishes charging".  That makes me think the OpenEVSE is opening the relay before the vehicle stops using energy?

**Comment by kallisti5** [comment]
I've updated the OpenEVSE firmware from D7.1.3 to 8.2.0 to see if the behavior changes

**Comment by kallisti5** [comment]
@glynhudson   I *might* know the cause of this one.  I did some testing on the latest firmware..

- Push the handle switch.. in about 1-2 seconds the relay disconnects (seems fine)
- I press clear in the app.  The relay *immediately* opens (pretty much as soon as I press the "clear" in the web app)


* In the first case, after pressing the handle button there was a brief delay between the handle button and the relay opening (assuming to tell the car reduce current before opening the relay)
* In the second case above, the car was reporting to pull 15A (current charge rate) when the relay opened. 

I use the manual override a lot via slapping the button on the EVSE :thinking:

**Comment by glynhudson** [comment]
This sounds like a hardware issue, probably a faulty contactor. Not a WiFi firmware issue. 

The J1772 button will immediately reduce the current, not need for the contactor to open before the cable in unplugged. It's the vehicle which is responsible for reducing the current not the EVSE https://openev.freshdesk.com/support/solutions/articles/6000052074-basics-of-sae-j1772

Using manual override should not cause any significant increase in wear on the contactor.
