### ISSUE TITLE
$SC RAPI command not working

### ISSUE THREAD

**Issue by Guiz22** [OpenEVSE/ESP32_WiFi_V4.x#394]
Hi, 
when i use the $SC RAPI command (wifi v4/openevse 8) to adjust max current capacity, it responds OK but it's mot working.
Everything was fine with wifi v3 / openevse v5.
Thanks for help :)

**Comment by jeremypoulter** [comment]
Setting via RAPI is not supported in v4 and may not work, please use the [HTTP API](https://openevse.stoplight.io/docs/openevse-wifi-v4/6e3b6e2f1b976-open-evse-wi-fi-esp-32-gateway-v4)
