### ISSUE TITLE
Manual Override

### ISSUE THREAD

**Issue by DmitryAVR** [OpenEVSE/ESP32_WiFi_V4.x#396]
Why do I have a "Clear" button instead of the "Start" button?

![image](https://user-images.githubusercontent.com/106111146/181012086-9c1d34c2-4b3c-4407-93cd-15a4b09efb6f.png)

**Comment by jeremypoulter** [comment]
That means the manual override is active and to stop it and return to the default behavior you press `Clear`

**Comment by DmitryAVR** [comment]
The "start" button is not used at all?

**Comment by jeremypoulter** [comment]
Once you have pressed clear it will change to Start or Pause depending on the state

**Comment by DmitryAVR** [comment]
Why do I have a "clear" button when I press the "pause" button, and not a "start" button?

**Comment by jeremypoulter** [comment]
Other systems can change the charge state in the background, so clearing the manual override does not necessarily change the charge state, eg you have PV divert enabled but start the charge manually with the manual override, in the meantime the sun comes up and the PV divert detects that you should be charging. in that case when you hit clear it would stop the manual override and fall back to PV divert, is still charging
