### ISSUE TITLE
4.1.4 seems to be missing openevse_huzzah32.bin?

### ISSUE THREAD

**Issue by mikebaz** [OpenEVSE/ESP32_WiFi_V4.x#397]
When I look at https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/tag/4.1.4 it looks like openevse_huzzah32.bin is missing from the assets.  Am I just being stupid or is it missing?

**Comment by danpadure** [comment]
it's missing, indeed!

**Comment by glynhudson** [comment]
It's now available, sorry for the hassle https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/tag/4.1.4
