### ISSUE TITLE
Does not report Wh to MQTT

### ISSUE THREAD

**Issue by andriuskr** [OpenEVSE/ESP32_WiFi_V4.x#399]
While charging, Wh topic is not updated to MQTT. It is alway the same value of 191895
. I assume it should represent charging power.
<img width="627" alt="Screenshot 2022-07-30 at 12 08 58" src="https://user-images.githubusercontent.com/13429780/181903778-ede6aeda-93df-4b87-85c3-4773e425efb5.png">
<img width="605" alt="Screenshot 2022-07-30 at 12 09 16" src="https://user-images.githubusercontent.com/13429780/181903780-ee4f22da-7435-4d76-a101-a3bec969f9e2.png">

**Comment by jeremypoulter** [comment]
This is the same as the `total_energy` topic, it is only updated at the end of the charging session.

**Comment by andriuskr** [comment]
Leaving no way to get current power usage ? :(

**Comment by jeremypoulter** [comment]
The session energy is available as `session_energy`, there is no instantaneous power, but both the current and the voltage are available for a simplistic power calculation

**Comment by KipK** [comment]
One could add a real time total counter, the total can't be used directly for counting consumtion prices. I had to make my own externally.

Having a real time counter has sense for external tools.

**Comment by jeremypoulter** [comment]
Related to #224
