### ISSUE TITLE
web UI localisation

### ISSUE THREAD

**Issue by KipK** [OpenEVSE/ESP32_WiFi_V4.x#400]
I have started to add localisation to the web UI ( english / french), using i18next-ko npm.

The WIP branches are here:

https://github.com/KipK/ESP32_WiFi_V4.x/tree/localisation
https://github.com/KipK/openevse_wifi_gui/tree/i18next-ko

If you have any suggestions while I'm on it.
Works well for now, but boring to complete :)

Got to say, this knockout.js is a pain compared to modern fw.

**Comment by KipK** [comment]
It's mostly ready. As it's based on Current Shaper branch, I will pull request this after the shaper ,merge.

**Comment by jeremypoulter** [comment]
Great work, this is something that has been missing for a while now, hopefully we get some more contributions for other languages now too.

Knockout.js is a means to an end, and a vast implement over what we had before ;-). Ultimately we need to rebuild the UI using more modern tools, probably based on Material UI.

**Comment by KipK** [comment]
I'd vote for a Svelte.js or Preact js fw with any light CSS fw like Purecss or Skeleton.
Material is a bit heavy but I think we can limitate that with tree-shaking.

Also first, UX should be revisited a bit, actual thing looks more like a patchwork of addition :)

**Comment by jeremypoulter** [comment]
Indeed the current UI is a patchwork of stuff that has evolved over the lifetime of the project. I have created #401 to track the requirements/ideas for the new UI.

**Comment by jeremypoulter** [comment]
Fixed via #422
