### ISSUE TITLE
NTP

### ISSUE THREAD

**Issue by DmitryAVR** [OpenEVSE/ESP32_WiFi_V4.x#403]
Why does my time decrease by 3 hours when setting the time using the browser? When setting the time using NTP, the time shows correctly

![image](https://user-images.githubusercontent.com/106111146/182337580-03997197-7a79-4e14-81c2-e63f1c7edcfd.png)

![image](https://user-images.githubusercontent.com/106111146/182338679-47762a6a-2cac-4d9b-958e-534193fb34ee.png)

**Comment by glynhudson** [comment]
Your browser timezone is incorrect? NTP is the best option to use anyway
