### ISSUE TITLE
RFID "hardware required" note

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#427]
We should add a note on the GUI to inform users that hardware is additional hardware is required to use the RFID function. Ideally we would be able to detect if RFID hardware was present and if not present gray out the RFID toggle.

**Comment by jeremypoulter** [comment]
I will have a look to see how easy it is to detect if the hardware is installed.

**Comment by Tifaifai** [comment]
with little list hardware requiered minimum into wiki or readme.md ;)
