### ISSUE TITLE
The delay timer does not work correctly when you set the time via a browser or manually

### ISSUE THREAD

**Issue by DmitryAVR** [OpenEVSE/ESP32_WiFi_V4.x#432]
When you reboot EVSE, EVSE enters the sleeping state. But the current time is included in the timer interval

**Comment by jeremypoulter** [comment]
Is this not the issue raised in #386?

**Comment by DmitryAVR** [comment]
No. The main thing there is the wrong time, which is set via the browser. I closed that question. Here, as I understand it, the timer does not work correctly when restarting, because there is no event "Scheduler woke: WakeReason_Event". 

![image](https://user-images.githubusercontent.com/106111146/192545116-65cfd48c-3ee1-4c4c-855c-d1312c437a4b.png)

But this event is in NTP. How can I enable this event when setting the time via the browser?

**Comment by DmitryAVR** [comment]
No. The main thing there is the wrong time, which is set via the browser. I closed that question. Here, as I understand it, the timer does not work correctly when restarting, because there is no event "Scheduler woke: WakeReason_Event". 

![image](https://user-images.githubusercontent.com/106111146/192545928-b03cba3d-c84c-40e5-9aab-60a2fb4c37f3.png)


But this event is in NTP. How can I enable this event when setting the time via the browser?

**Comment by glynhudson** [comment]
This should be fixed in the latest version
