### ISSUE TITLE
Enhancement: Uptime status clock

### ISSUE THREAD

**Issue by DrFrankReade** [OpenEVSE/ESP32_WiFi_V4.x#434]
Would be nice, especially in these times of heavy development, to have a way to see uptime of the ESP32 and wifi connections.

**Comment by jeremypoulter** [comment]
Should be able to add this to the `/status` endpoint and the status reports over MQTT/EmonCMS, etc

**Comment by mathieucarbou** [comment]
@jeremypoulter @KipK : I am also interested in having an uptime (also exposed through mqtt, besides the status api).

It's been several time already that I would like to know (and monitor) when was the last restart of the box in Home Assistant and there is no way currently to do that.

I can send a PR  for review if this is something that you guys are willing to merge?

**Comment by jeremypoulter** [comment]
@mathieucarbou a PR would be great.

**Comment by mathieucarbou** [comment]
PR sent: https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/700
