### ISSUE TITLE
Unstable env:openevse_nodemcu-32s

### ISSUE THREAD

**Issue by DrFrankReade** [OpenEVSE/ESP32_WiFi_V4.x#435]
Getting instability, I suspect that it's the non-definition of defaults for buttons and improper or non-use of pullup/down on the many flavors of nodemcu-32s boards out there. 

Suggest defining the defaults in platformio.ini  so that **dummies like me** know to at least change them. 

```
[env:openevse_nodemcu-32s]
board = nodemcu-32s
build_flags =
  ${common.build_flags}
  ${common.version}.dev
  ${common.src_build_flags}
  ${common.debug_flags}
  -D WIFI_LED=2
  -D WIFI_LED_ON_STATE=LOW
  -D RAPI_PORT=Serial2
  -D WIFI_BUTTON=0
  -D WIFI_BUTTON_PRESSED_STATE=LOW
```

**Comment by jeremypoulter** [comment]
Thanks for the input, if you have working settings for this board then a PR would be great, however there may be different versions of the board so can you clarify the source/revision of your board?

**Comment by DrFrankReade** [comment]
Unfortunately, the board is so desperately generic that it goes by no other name, as far as I can tell, than the NODEMCU-32s

The best way I can differentiate it from others is by the position of the yellow capacitor and the voltage regulator. 

![Screenshot from 2022-09-28 21-09-50](https://user-images.githubusercontent.com/10439664/192936857-77f69cd1-d8e4-4dfc-96a7-7c59a6f88db0.png)
```
[env:openevse_nodemcu-32s]
board = nodemcu-32s
build_flags =
  ${common.build_flags}
  ${common.version}.dev
  ${common.src_build_flags}
  ${common.debug_flags}
  -D WIFI_LED=2
  -D WIFI_LED_ON_STATE=LOW
  -D RAPI_PORT=Serial2
  -D WIFI_BUTTON=0
  -D WIFI_BUTTON_PRESSED_STATE=LOW
```
The above settings have been fairly stable over the last 12 hours, which is better, but hardly saying much.

**Comment by DrFrankReade** [comment]
Update: Experiencing the same on a brand new "official" OpenEVSEWifi board (came with 4.1.2) and broke with 4.1.5. Suspect it's not hardware.
