### ISSUE TITLE
API feature req: update external value from http API

### ISSUE THREAD

**Issue by KipK** [OpenEVSE/ESP32_WiFi_V4.x#439]
I've received this request from another forum. 

We should be able to update external values like Voltage, Vehicule SOC, +I/-E and co from HTTP POST requests and not only MQTT.

Before those guys where using RAPI to update voltage, but not available yet using new API

**Comment by Sattaz** [comment]
I'm the guy from that other forum and I developped a plugin for the Jeedom home automation system using the EVSE RAPI.
I was adapting my plugin to use the new 'WIFI' API but could not found any http/post method to update such settings as the Voltage, etc ... as referred by KipK.
This is essential to get the EVSE module precisely doing internal calculation like the charge session.
Could you implement this? Thx a lot!

**Comment by jeremypoulter** [comment]
I guess we could do this, similar to the config API I could allow a `POST` on the `/status` endpoint to update those values that can be updated by MQTT.

**Comment by jeremypoulter** [comment]
Also if Web Sockets are an option I am also planning on adding support for reading from EmonESP #304.

**Comment by fhteagle** [comment]
+1 for this, especially being able to control the max amps value via HTTP post or get.

Any security considerations with enabling this though?

**Comment by KipK** [comment]
> 

You already can set max_current using claims or override from the API
