### ISSUE TITLE
Can't set auto_release parameter with /override api endpoint

### ISSUE THREAD

**Issue by KipK** [OpenEVSE/ESP32_WiFi_V4.x#446]
Override has auto_release always true whatever you set over the API.
Works using /claims endpoint btw

**Comment by KipK** [comment]
Dunno if it was intentional, but I see some cases were overrides should be set to auto_release: false

**Comment by jeremypoulter** [comment]
Yes, this was an intentional choice for the override module, the effects should be cleared when the session ends and the device returns to the default behaviour

**Comment by KipK** [comment]
ok, commented in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/447
Thanks
