### ISSUE TITLE
Emoncms won't connect in 4.1.5, roll back to 4.1.2 and its OK.

### ISSUE THREAD

**Issue by DrFrankReade** [OpenEVSE/ESP32_WiFi_V4.x#464]
On a new "Official" OpenEVSE Wifi board:

1. Purchased, came with 4.1.2 out of the box.
2. connected to wifi only (no services configured)
3. and updated to 4.1.5

**Wifi and stability issues after a few minutes**
**Unable to get emoncms to connect** It just can't connect. Connected? No.
Tried raw IP and .local 
MQTT working
Dynamic charge current working

I downgraded back to 4.1.2. 
Didn't have to reconfigure anything (except emoncms)
Stability returned. 
emoncms worked again
MQTT still fine
Current control no longer available.

So what do we make of it?

**Comment by glynhudson** [comment]
This is a duplication of https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/463
