### ISSUE TITLE
Manual Override button says "Start" but should actually say "Pause"

### ISSUE THREAD

**Issue by Edison517** [OpenEVSE/ESP32_WiFi_V4.x#466]
This button usually toggles to say the opposite of the current state, so that you can start a paused session, or pause a current charging session. But when I first load the page, the button already says "Start", even though a charge session just started after plugging my car in.

Does this toggle button need updated or is it just me? I'm on 4.1.5.

**Comment by jeremypoulter** [comment]
Thanks for the report, can you send the output of the `/claims`, `/claims/target` and `/status` endpoints? IE go to http://<IP of OpenEVSE>/status in the browser

**Comment by jeremypoulter** [comment]
Also a screenshot would also be helpful

**Comment by jeremypoulter** [comment]
Thanks, I will take a look

**Comment by jeremypoulter** [comment]
I have been able to replicate this issue. I think this is just a display issue, the button operates as expected. The translation cond is forcing the default value to `Start`, any state updatewill fix the issue. Just having a look to see if I can fix this.

**Comment by jeremypoulter** [comment]
@KipK I had to add `pause` to the English translations

**Comment by davidwkerr** [comment]
I have just upgraded from 8266 WiFi to ESP32. Using 4.1.6. This Start/Pause button problem is driving me nuts on both my Zoe and my Tesla. So, just adding my voice to hoping it can be fixed in the next release.

**Comment by jeremypoulter** [comment]
Oops will get the fix for this merged.

**Comment by davidwkerr** [comment]
Thanks!
