### ISSUE TITLE
Controller restart ignored eco divert mode setting at boot

### ISSUE THREAD

**Issue by ruimarinho** [OpenEVSE/ESP32_WiFi_V4.x#481]
If OpenEVSE is in Eco (PV Divert) mode and the controller is restarted, those settings are ignored (but are successfully restored) and the car starts charging right away:

**Before restart** 

<img width="953" alt="image" src="https://user-images.githubusercontent.com/288709/202015883-b110ff7d-d46b-4a18-a0d0-1f44ca163331.png">

**After restart**

<img width="934" alt="image" src="https://user-images.githubusercontent.com/288709/202016303-99626773-a959-4de6-b5c3-2a80bb200245.png">

As you can see, Eco mode is still active after restarting the controller, but the boot logic ignored it was active and there was no energy being exported at all.

**Comment by KipK** [comment]
this is default behavior, if you want to disable Divert that survive reboot, it's on the Config / Services part.

**Comment by ruimarinho** [comment]
Not sure I follow -- in order to enable this mode, the service needs to be enabled, but that hasn't changed, has it?

<img width="456" alt="image" src="https://user-images.githubusercontent.com/288709/202208248-05e9ec7c-e36d-4999-a825-76784194a51f.png">

**Comment by KipK** [comment]
ho I have missread sorry this effectively shouldnb't happen

**Comment by KipK** [comment]
Prolly related to #452 and #450

Seems EVSE is always starting to max amp whatever the current claim is. Sending another claim after start get back to normal behavior.
