### ISSUE TITLE
Very high sensor offset

### ISSUE THREAD

**Issue by ruimarinho** [OpenEVSE/ESP32_WiFi_V4.x#482]
Hi,

What is the meaning of a sensor offset of `7385643`?

<img width="221" alt="Screenshot 2022-11-15 at 22 09 57" src="https://user-images.githubusercontent.com/288709/202036417-49aecfdc-8830-49c8-8c17-842f7ebc0c43.png">

**Comment by glynhudson** [comment]
That's the total energy in Ws as a response to `$GU`, see 

https://github.com/OpenEVSE/open_evse/blob/master/firmware/open_evse/rapi_proc.h#L325

In latest FW the energy totals are stored on the WiFi module rather than the OpenEVSE controller
