### ISSUE TITLE
Feature Request : Daily Energy Counter

### ISSUE THREAD

**Issue by TommySharpNZ** [OpenEVSE/ESP32_WiFi_V4.x#484]
We have a session and total energy counter in kWh....
I'd really appreciate if we could also have a "daily" counter that resets daily at midnight.

**Comment by TommySharpNZ** [comment]
Any further thoughts on getting a daily counter added similar to the session and total counters?

**Comment by firstof9** [comment]
I could go for a session counter that counts up while charging.

**Comment by TommySharpNZ** [comment]
Based on me trying to chart the Total Usage am I correct in deducing that the counters are only updated at the end of each charging session?
With so many "time of use" tarrifs now it would be more ideal to update the counters every 10 seconds or something like that...
![image](https://user-images.githubusercontent.com/15130284/218907005-82e897e8-fe73-4a08-9a83-ad4443f4c02d.png)
