### ISSUE TITLE
Hardware info

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP32_WiFi_V4.x#49]
We should add some hardware info to the `config` so we can distinguish between the ESP8622 and ESP32

**Comment by glynhudson** [comment]
Good idea, however at present V3.x is ESP32 while V2.x is ESP8266

**Comment by jeremypoulter** [comment]
Correct, just would be nice to be more explicit, there is also the Node.JS version.

**Comment by Niko-La** [comment]
In a similar request, it would be nice once the mqtt is established if the charger sends an initial post that could also include the local ip of the webserver.  My router does not workd with openevse.local so I have to either run fing or go to the box which is not terrible but would be a nice feature.

Maybe it cant be new rapi command like $IP?

**Comment by jeremypoulter** [comment]
@Niko-La we already do this, see #15, although this info should be added to the docs.
