### ISSUE TITLE
OpenEVSE Wifi V1 wrong regulatory domain

### ISSUE THREAD

**Issue by fhteagle** [OpenEVSE/ESP32_WiFi_V4.x#490]
The OpenEVSE defaults to transmitting CN regulatory domain when it is making an AP. This caused some minor havoc with Intel's ridiculous Location Aware Regulation system in my laptop's wifi card. Can 802.11d / 802.11h fields be set in the ESP32 configuration somehow? If not, can these be disabled?

**Comment by KipK** [comment]
I've checked on espressif doc and seems the best mode to use for all is  "World safe mode"
