### ISSUE TITLE
Time format in Timer

### ISSUE THREAD

**Issue by TommySharpNZ** [OpenEVSE/ESP32_WiFi_V4.x#491]
I have setup a timer for 9pm to 6am. But when I look at the timer now it's not clear if it's 9am or 9pm? Maybe this should be 24 hour format?
![image](https://user-images.githubusercontent.com/15130284/205144150-155a461c-f313-4504-858d-a0612e622fed.png)

**Comment by TommySharpNZ** [comment]
In the new UI currently being worked in looks like this may be resolved :-)
Although I'm not sure when that will be available for general release.

![image](https://user-images.githubusercontent.com/15130284/205144498-808edde7-0ef7-480a-a3e4-a09e0f26e2ea.png)

**Comment by davethetallguy** [comment]
What version? Mine (version 4.1.5) pretty clearly has AM/PM indication. Does this infer without the indication that it is in 24 hour mode?  
![Screenshot 2022-12-01 at 11 55 33 AM](https://user-images.githubusercontent.com/64752714/205147647-2536dbc5-0312-4e05-a130-50c695973074.png)

**Comment by TommySharpNZ** [comment]
When I am setting up the Timer it does show am/pm....
Bat after that is toes not...
Could be Firefox issue maybe?

**Comment by jeremypoulter** [comment]
Yeah, we use the browser's input for the time as these should give the appropriate experience for the platform

**Comment by TommySharpNZ** [comment]
Confirmed it works fine in the Edge browser.

**Comment by jeremypoulter** [comment]
Just tried Firefox and at least with my settings, it displays in 24 hour:
![image](https://user-images.githubusercontent.com/6116992/205268303-d08c41dc-bbf1-42dc-879a-492bca7dbbe1.png)

But equally, so does Chrome:
![image](https://user-images.githubusercontent.com/6116992/205268496-c1b255ba-e532-401e-8b4a-64f956810047.png)

**Comment by KipK** [comment]
new UI use now locale settings to display time in 24H or 12 am/pm format.
