### ISSUE TITLE
Release 4.1.7 spams MQTT with non-stop evse/claim: {"state":"null"} messages many times per second

### ISSUE THREAD

**Issue by rigorka** [OpenEVSE/ESP32_WiFi_V4.x#505]
Steps to reproduce: 
- Initially I had 4.0.0 installed, upgraded that via the web UI to 4.1.7. However I can also confirm that building the fw from the current master git branch and installing it to a freshly unpacked ESP32 produces the same results.
- My MQTT handler has collapsed immediately overloaded by hundreds of evse/claim: {"state":"null"} messages.
- I've tried Factory Reset which did not fix the situation
- Making and then releasing a Claim via HTTP API fixes the problem until the next reboot
- After rebooting the Openevse Wifi it spams the MQTT queue again

Downgrading to release 4.1.6 fixes the problem.

**Comment by glynhudson** [comment]
@KipK could this be related to https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/488 ?

**Comment by KipK** [comment]
Mhhh I don't think so. I'm jumping in a plane right now but will get a look tomorrow. 
I haven't saw such behavior here,  but there's definitely something wrong here I have to track down.

**Comment by KipK** [comment]
Ok I've found it's prolly there:
https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/65ca1bc4a877eb618a3c44be11019481dd75d11c/src/mqtt.cpp#L501

I'll fix that

**Comment by KipK** [comment]
Forget it, I've found. I forgot to inialise claims_version ...
Fix is coming

**Comment by KipK** [comment]
It stills not fixed I can see the debug log with mqtt activated spaming claims has changed, posting claims. I'm looking at it.
