### ISSUE TITLE
Current Shaper is not working as expected

### ISSUE THREAD

**Issue by tux43** [OpenEVSE/ESP32_WiFi_V4.x#508]
Hi,
I've setup up 'Current Shaper' as per below.

<img width="1113" alt="Screenshot 2023-01-05 at 7 36 00 pm" src="https://user-images.githubusercontent.com/53364421/210742400-1cad03bd-d191-4a81-ae3c-2c46e92e610d.png">

Unfortunately when I set the MQTT topic it isn't taking effect.

**Comment by KipK** [comment]
You've set it wrong, the livepowerload topic shouldn't be in the path of Base Topic ( i e openevse_9c0c in your case ) , this is the topic where OpenEVSE publish data. 

The Live Power Load topic is not populated by openevse but your external smart home controller, so it should be on another base topic like homeass/energy/livepower

**Comment by tux43** [comment]
> The Live Power Load topic is not populated by openevse but your external smart home controller or emoncms, so it should be on another base topic like homeass/energy/livepower

Does it take the mqtt server from the enabled one (right hand pane?). The way the page displays it looks independent without a mqtt server specified. I’ll give this a shot in the morning when the sun is up!

Thanks

**Comment by KipK** [comment]
Yes it does indeed.

**Comment by tux43** [comment]
Unfortunately I am still having trouble with "Current Shaper". I have defined a topic within MQTT "homeenergy/energy/power" and set a nominal value of 1200 (watts).

<img width="1017" alt="Screenshot 2023-01-06 at 12 07 10 pm" src="https://user-images.githubusercontent.com/53364421/210912246-65bbd906-ee20-4615-9771-96d44f952811.png">

I have setup OpenEVSE as per this screen with the intention of reducing the watts to the "Current Shaper"

<img width="1085" alt="Screenshot 2023-01-06 at 12 10 39 pm" src="https://user-images.githubusercontent.com/53364421/210912444-8775753d-f3bf-412c-b948-ff8646c7d9ee.png">

It still charges at the full rate.

<img width="1017" alt="Screenshot 2023-01-06 at 12 07 10 pm" src="https://user-images.githubusercontent.com/53364421/210912246-65bbd906-ee20-4615-9771-96d44f952811.png">

What am I missing?

**Comment by tux43** [comment]
> The live power data needs te be refreshed each 360sec max or shaper will Pause EVSE .
> Posting fake data once won't work.

Ok, great. Although I am still having major issues trying to get it to operate effectively. It seems to be reading all the MQTT topics however it does not start charging with a "Waiting for Solar message as per below"

Here is what I have done.

I have defined the following MQTT topics all in watts. These are updated every 30 seconds.

homeenergy/energy/availablepower (Feed in or consumption from the grid - can be positive or negative)
homeenergy/energy/totalsolaroutput (Solar output and will always be positive)
homeenergy/energy/housepowerload (House consumption this and always negative)

<img width="231" alt="Screenshot 2023-01-07 at 10 53 48 am" src="https://user-images.githubusercontent.com/53364421/211121475-fee82a4d-2e8a-4e02-b398-6b6a655ad7ec.png">

I have then defined MQTT as per below and consumed a voltage topic so I get an acurate reading.

<img width="447" alt="Screenshot 2023-01-07 at 11 00 04 am" src="https://user-images.githubusercontent.com/53364421/211121881-4a7a7495-054b-45a2-8504-71045ea65a48.png">

I have defined Solar PV Divert to read from the Total Solar output as per below.

<img width="446" alt="Screenshot 2023-01-07 at 11 02 28 am" src="https://user-images.githubusercontent.com/53364421/211122035-e610a714-61ed-429c-8076-59033a4d83cc.png">

I have defined the current shaper to montior the household load, I assume this is subtracted from total solar output to determine the current to send to the vehicle?

<img width="448" alt="Screenshot 2023-01-07 at 11 03 42 am" src="https://user-images.githubusercontent.com/53364421/211122059-e66df97c-3855-4c52-a28a-e1b0b0884f2b.png">

After doing all of this OpenEVSE is reading the values however keeps stating it is "Waiting for solar"? 

<img width="994" alt="Screenshot 2023-01-07 at 11 09 11 am" src="https://user-images.githubusercontent.com/53364421/211122583-9dffcab8-6918-4743-a3bb-8b226cbca343.png">

**Comment by KipK** [comment]
Shaper is disabled when Divert is active*Your problem now concern Divert then, out of topic so.

btw, your solar input is 811W , not enough to start a charge as minimum is 6A, ie 1428w for 220w so it's totally normal nothing happends here.
