### ISSUE TITLE
/evse/console websocket issue

### ISSUE THREAD

**Issue by KipK** [OpenEVSE/ESP32_WiFi_V4.x#509]
Websocket with evse console close with thrown error:
` Could not decode a text frame as UTF-8. `

Seems /evse/console endpoint should filter its output from those unkown characters

**Comment by jeremypoulter** [comment]
Which browser/client is that with? I remember seeing something like this with a Node JS client but think it worked ok with most browsers

**Comment by KipK** [comment]
All legacy browsers, it's mandatory to reject non UTF8 message now over web socket 
It's also the case on old UI , you just have to throw the web console.
It stills update on screen because it fetches from HTTP get at each reconnection.

**Comment by jeremypoulter** [comment]
:( ok will take a look

**Comment by jeremypoulter** [comment]
Guess I need to do the reverse of this: https://github.com/jeremypoulter/OpenEVSE_Lib/blob/master/src/openevse.cpp#L831-L836 won't be a true representive of what is being sent on the serial... 

Another option may be to send as binary and handle any processing in the browser, may be a bit easier with more memory/processing

**Comment by KipK** [comment]
Why not just finding a magic char in the utf8 table?

**Comment by jeremypoulter** [comment]
Would have to copy all the data as utf-8 will be larger than the raw data. I will have a look at it again and see how plausible this is, but would like to keep this fairly light weight on the WiFi module side...

**Comment by KipK** [comment]
I can try to use binary over ws if you can post a patch with binary output on this endpoint to test with.

**Comment by KipK** [comment]
Or we just poll the http endpoint, without ws ( not really clean though )
