### ISSUE TITLE
Mennekes motor still locked when PowerLost

### ISSUE THREAD

**Issue by DylanVautrin** [OpenEVSE/ESP32_WiFi_V4.x#527]
Hello, i have an issue with the PowerLoss behaviour, if the power is cutting down during the charge, the Mennekes locker do not unlock, is there any solution to unlock if we loose the power during a charging session ? 
Thanks
Best regards

**Comment by DylanVautrin** [comment]
Hi, i've made some test and i found a way to do it, i think it is not the best : 

<img width="469" alt="image" src="https://user-images.githubusercontent.com/87700854/214598771-e7ee1f78-9a58-4b90-88b2-e81411e1f119.png">

I'm using the OpenEVSE with a OCPP backend and i noticed that when the power is cutting down, the OpenEVSE send a Status Faulted with error code Ground Failure, so i detect this state to unlock the Mennekes motor.
Is there a better way to do it ? 
Thanks

**Comment by chris1howell** [comment]
Mennekes Motor is a Forward/Reverse locking setup. It requires power to
lock and unlock, which you do not have when PowerLost. The solution
proposed would work with the addition of a backup battery to power the
controller and Mennekes lock while input power is gone.

**Comment by DylanVautrin** [comment]
Ok thanks ! At the end, i should have a battery but for now it work well without (with this modification).
Thanks again !

**Comment by glynhudson** [comment]
I've seen some Mennekes lock implementations with a hidden physical cable to allow unlocking in the event of power failure.
