### ISSUE TITLE
Time Manager manual bug spam log

### ISSUE THREAD

**Issue by KipK** [OpenEVSE/ESP32_WiFi_V4.x#529]
I felt the EVSE unresponsive when setting to manual mode. 
Could reproduce the issue, just set the time to manual, and reboot OpenEvse Wifi  ( tz is set to utc ) 
if firmware is compiled with  -D ENABLE_DEBUG_TIME, the log is spammed at high frequency by:

Time manager woke: WakeReason_Scheduled
Local time: 28-Jan-23, 22:27:40
_nextCheckTime = 4716
_setTheTime = 0
Time manager woke: WakeReason_Scheduled
Local time: 28-Jan-23, 22:27:40
_nextCheckTime = 4716
_setTheTime = 0
Time manager woke: WakeReason_Scheduled
Local time: 28-Jan-23, 22:27:40
_nextCheckTime = 4716
_setTheTime = 0

**Comment by jeremypoulter** [comment]
Happended to be looking in that area, fairly simple fix, not sure it would have had a massive performance hit though

**Comment by KipK** [comment]
That was on UI side, console spam was slowing down the browser, thanks
