### ISSUE TITLE
Current shaper with 3-phase current setup

### ISSUE THREAD

**Issue by dafal** [OpenEVSE/ESP32_WiFi_V4.x#539]
I tried the current shaper module.  Thx for this great idea !  However after few hours spent I spotted that it is most probably not compatible with a 3-phase setup. I guess the function CurrentShaperTask::shapeCurrent() is not returning the correct share_current.  It could be interesting to have the option to select 3-phase mode.  In this case, the returned current should be adapted.

**Comment by KipK** [comment]
Issue solved in master, can be closed
