### ISSUE TITLE
Issues with connecting to OCPP server

### ISSUE THREAD

**Issue by merlinmag** [OpenEVSE/ESP32_WiFi_V4.x#553]
I setup OpenEVSE device with WiFi module, running firmware  4.1.2. The setup is incomplete - there are only OpenEVSE controller and the WiFi module, even Earth connection is missing. It is done on purpose just to experiment with the software.
I have setup Steve OCPP server https://github.com/steve-community/steve and later on also this server https://github.com/mobilityhouse/ocpp . 

While the OpenEVSE is set up to connect to OCPP server,it is unable to connect. Both of the servers report invalid messages coming from Charge Point, hence preventing the connection. 

Does anyone observed such problem?

**Comment by jeremypoulter** [comment]
Are you able to check with the [latest](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/tag/latest) build? That has an updated OCPP library

**Comment by merlinmag** [comment]
Which bin shall I take for my hardware, I got lost a bit:
![image](https://user-images.githubusercontent.com/1721207/221435737-2526b6e9-eae1-484c-af6a-20d92be849b4.png)

[openevse_wifi_v1_openevse-gui-v2.bin](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/download/latest/openevse_wifi_v1_openevse-gui-v2.bin)

or 

[openevse_wifi_v1_openevse_wifi_gui.bin](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/download/latest/openevse_wifi_v1_openevse_wifi_gui.bin)

**Comment by merlinmag** [comment]
Problem solved, most probably the Steve was not correctly installed.

**Comment by jeremypoulter** [comment]
Good to know, for the record, either of those would do, the difference is the UI.
