### ISSUE TITLE
New GUI and MQTT

### ISSUE THREAD

**Issue by doppiaemme** [OpenEVSE/ESP32_WiFi_V4.x#554]
Hi,

I can't manage to have MQTT connected using the new GUI!
While I have several other devices running fine with the broker, I can't manage to make this work.
Checking the log of the mosquitto broker there is never any attempt from the IP address of openevse.
No Idea how to debug it from this side?
thanks in advance for any clue

<img width="643" alt="image" src="https://user-images.githubusercontent.com/3978350/221446724-795afb1f-38bb-4279-8a6d-c9dd20dd1666.png">

<img width="506" alt="image" src="https://user-images.githubusercontent.com/3978350/221446734-8dbd279a-ef99-43a2-959f-a8b4fb02e8a0.png">

**Comment by KipK** [comment]
I use credentials and works ok. Can you show the full mqtt config screen ?

**Comment by doppiaemme** [comment]
There is no much to configure to be honest....
it was working before, the only two things that changed are:
-upgraded the new GUI 
-switched from mosquitto anonymous to mosquito with login/passw (as the Homeassistant's mosquitto addon doesn't allow anonymous anymore). Other MQTT devices are perfectly joining the broker, only openevse gives me an error and no trace of attempred logins on mosquitto's logs

<img width="570" alt="image" src="https://user-images.githubusercontent.com/3978350/222159941-a430478b-a1f6-401f-97bb-9a9e3081291d.png">

**Comment by KipK** [comment]
check your login is not limited to one session only or use different credentials per device

**Comment by doppiaemme** [comment]
downgraded to the old GUI and it worked immediately

2023-03-01 22:53:17: New connection from 192.168.3.71:57195 on port 1883.
2023-03-01 22:53:17: New client connected from 192.168.3.71:57195 as openevse-8dd8 (p2, c0, k60, u'mosquitto').

<img width="364" alt="image" src="https://user-images.githubusercontent.com/3978350/222273816-96f83c1d-ab5a-4354-8cf6-89e27e8cf322.png">

**Comment by KipK** [comment]
gui only store config data in /config endpoint, problem should not come from there. It has nothing to do on how service works on the fw.
What previous version are you trying ?

**Comment by KipK** [comment]
can you export the config from /configuraiton/firmware , or just paste the result of http://openevse/config and /status
when it's not working

**Comment by doppiaemme** [comment]
I just reflashed v2 and now it works. no idea what happened but seems like something was corrupted during the first upgrade!
thanks anyhow!

**Comment by KipK** [comment]
There's a bug laying around clearing some settings during flash upgrade.
I advice to grab a backup from the new UI, add your password key locally in the json file. And import it after an update until it's solved.

**Comment by pdhoogh** [comment]
Yes, I found a reset to factory settings and put everything back in worked for me. I have done it on three occasions.

**Comment by KipK** [comment]
you shouldn't need to factory reset, just importing again is sufficient.
