### ISSUE TITLE
Scheduler wrong calculation of current event

### ISSUE THREAD

**Issue by KipK** [OpenEVSE/ESP32_WiFi_V4.x#560]
Related to discussions here for more details: https://github.com/KipK/openevse-gui-v2/issues/31

**How to reproduce:**
Set a timer to Active few minutes before current time , with same current hour.
Set a second timer to Disabled that should happend later in the day.

It will set the state of evse to disabled instead of using first timer. 

/schedule:
`[{"id":1,"state":"active","time":"09:31:00","days":["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]},{"id":2,"state":"disabled","time":"15:00:00","days":["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]}]`

/schedule/plan:

`{"current_day":"wednesday","current_offset":59834,"next_event_delay":61323,"current_event":{"id":2,"state":"disabled","time":"15:00:00","day":"wednesday","offset":54000,"start_offset":54000,"diff":0,"duration":67157},"next_event":{"id":1,"state":"active","time":"09:31:00","day":"thursday","offset":34260,"start_offset":34757,"diff":497,"duration":19243},"sunday":[{"id":1,"state":"active","time":"09:31:00","day":"sunday","offset":34260,"start_offset":33256,"diff":-1004,"duration":20744},{"id":2,"state":"disabled","time":"15:00:00","day":"sunday","offset":54000,"start_offset":54000,"diff":0,"duration":67677}],"monday":[{"id":1,"state":"active","time":"09:31:00","day":"monday","offset":34260,"start_offset":35277,"diff":1017,"duration":18723},{"id":2,"state":"disabled","time":"15:00:00","day":"monday","offset":54000,"start_offset":54000,"diff":0,"duration":67480}],"tuesday":[{"id":1,"state":"active","time":"09:31:00","day":"tuesday","offset":34260,"start_offset":35080,"diff":820,"duration":18920},{"id":2,"state":"disabled","time":"15:00:00","day":"tuesday","offset":54000,"start_offset":54000,"diff":0,"duration":67741}],"wednesday":[{"id":1,"state":"active","time":"09:31:00","day":"wednesday","offset":34260,"start_offset":35341,"diff":1081,"duration":18659},{"id":2,"state":"disabled","time":"15:00:00","day":"wednesday","offset":54000,"start_offset":54000,"diff":0,"duration":67157}],"thursday":[{"id":1,"state":"active","time":"09:31:00","day":"thursday","offset":34260,"start_offset":34757,"diff":497,"duration":19243},{"id":2,"state":"disabled","time":"15:00:00","day":"thursday","offset":54000,"start_offset":54000,"diff":0,"duration":67396}],"friday":[{"id":1,"state":"active","time":"09:31:00","day":"friday","offset":34260,"start_offset":34996,"diff":736,"duration":19004},{"id":2,"state":"disabled","time":"15:00:00","day":"friday","offset":54000,"start_offset":54000,"diff":0,"duration":65733}],"saturday":[{"id":1,"state":"active","time":"09:31:00","day":"saturday","offset":34260,"start_offset":33333,"diff":-927,"duration":20667},{"id":2,"state":"disabled","time":"15:00:00","day":"saturday","offset":54000,"start_offset":54000,"diff":0,"duration":65656}]}`

**Comment by KipK** [comment]
It looks like it's related to Time Zone.
On my case the timers start 2 hours later than planned ( I'm on GMT +2 )

**Comment by fhteagle** [comment]
I think you are correct that it is a TZ problem in the scheduler calculation. I tested both 2 and 3 timer schedules, and was able to affect the results by moving an active line across a time zone gap. I.e. I am in UTC-7 at the moment. If the active was less than now +7 hours, it was incorrectly applied and activated the unit. If the active was more than now +7 hours, it was correctly disregarded for the calculation.

**Comment by KipK** [comment]
I can change the UI to send utc time for /schedule endpoint and parse time back to local time, but is it what's the api expect @jeremypoulter ? looks to be a bit boilerplaty but perhaps there's a reason to not use local timer in scheduler ?

**Comment by KipK** [comment]
I remember I have changed the time handling in the scheduler part of ui few days ago, I bet that's what introduced the bug and it is UI bug only,  it was working ok before. :)

**Comment by KipK** [comment]
I have checked in scheduler.cpp and 
localtime_r(&utc_time.tv_sec, &local_time)

reports 14h20 instead of 15h20 here, ( i'm UTC+1 in winter) 

but reading the code seems to me it expects local time in timers so we ahve a problem here

**Comment by jeremypoulter** [comment]
:( arrrr timezones.... Will take a look

**Comment by jeremypoulter** [comment]
I fixes a few time zone related issues in #569, can you check?

**Comment by KipK** [comment]
still same problem.

**Comment by KipK** [comment]
have set a timer at 19:02 to enable,  and disable at 6am, it is 19h11, state is still disabled

**Comment by KipK** [comment]
interesting, if i set time to manual it then works. But manual has no timezone  isn't, it ?

**Comment by KipK** [comment]
oups forget it, i haven't test with your PR, thought you've updated the master :)

**Comment by KipK** [comment]
fixed by #569

**Comment by fhteagle** [comment]
The dev build from yesterday still has this bug apparently. Is there a different build I need to be testing to verify this fix?

**Comment by KipK** [comment]
@fhteagle you can try my build from today it has all the fixes waiting to me merged

https://drive.google.com/open?id=1FZYEWYd9MTqPxts0MquPUQlYGsO7DoNm&authuser=hotlobster75%40gmail.com&usp=drive_fs

**Comment by fhteagle** [comment]
@KipK  -

Scheduler seems to be working better in this version, yes. I was not able to induce any of the scheduling failures that we have been seeing.
