### ISSUE TITLE
V2 Scheduler times do not line up with actual time.

### ISSUE THREAD

**Issue by jasonwray** [OpenEVSE/ESP32_WiFi_V4.x#574]
Hi all,

I've been testing the V2 WiFi firmware and have noticed that the times set in the scheduler do not take effect at the correct time.

In my case they appear to be 4 hours ahead.
My unit is set to NTP using America/Detroit.

Cheers

**Comment by jasonwray** [comment]
Ah it looks like this is a duplicate of #560 but that bug is marked closed?

**Comment by jeremypoulter** [comment]
Yeah, not sure why #560 was closed, reopened it, but please give PR #569 a try

**Comment by KipK** [comment]
I closed it as it was fixed by #569 , thought it was merged.
