### ISSUE TITLE
v2gui not updating time on unit

### ISSUE THREAD

**Issue by schmellic** [OpenEVSE/ESP32_WiFi_V4.x#581]
UK entered DST this week and the charge unit was still showing the old time despite UI showing correct time.  Tried manual setting and changing time zone but no change on unit.

Rolled back to 4.1.7 and time updated correctly in both UI and on the unit

**Comment by jeremypoulter** [comment]
Can you confirm which binary you were using?

**Comment by schmellic** [comment]
Downloaded on the 24th March

**Comment by jeremypoulter** [comment]
Thanks, I suspect that this will be resolved by #569

**Comment by schmellic** [comment]
Thanks, will check again once fix get's merged

**Comment by glynhudson** [comment]
It's now been merged
