### ISSUE TITLE
Auto version number not added when built by GitHub

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP32_WiFi_V4.x#584]
When the firmware is built by the GitHub workflow no version information is added to the build with an error `fatal: No names found, cannot describe anything.`

This looks to be because GitHub checks out with depth=1, https://stackoverflow.com/questions/66349002/get-latest-tag-git-describe-tags-when-repo-is-cloned-with-depth-1

I think we may need to update to use the `GITHUB_REF_NAME` env var, if that is set, and is start with `v` then use as is, if it does not start with `v` then append the git hash (`git rev-parse HEAD`). If `GITHUB_REF_NAME is not set then`git describe --tags` with a fallback to `git rev-parse HEAD`.

**Comment by KipK** [comment]
Looks good yes, and as told you in pm, we need a field in the github release endpoint api having the version number :
https://api.github.com/repos/OpenEVSE/ESP32_WiFi_V4.x/releases

could be "assets" objects "label" property ( should be the same for each binary ) 
or directly in the tag_name but it will messup the release/build page with different tags for each dev build

**Comment by KipK** [comment]
Here is  how it looks with daily builds:

![image](https://user-images.githubusercontent.com/488789/228760867-bb5ab2d5-2901-42ce-b597-d601f7d6c69b.png)

I need to match the Installed field ( taking the build version from the fw ) with the Latest one ( took from github api  , for now it takes "name" field , this should be changed.
