### ISSUE TITLE
Pilot Limit out by 3 amps

### ISSUE THREAD

**Issue by dmelliott20** [OpenEVSE/ESP32_WiFi_V4.x#588]
Version 8.2.2.EU 
Wi-Fi 4.1.7

Just took delivery of a new bmw ix3 that shows the limit of charge that is being requested by the pilot from openevse.

it is consistently 3 below what is set….

set limit 6 amp - car does not charge
set limit 9 amp - car reports 6amp limit
Set limit 20 amp - car reports 17amp limit

I assumed this was just my Audi behaviour previously as I couldn’t see the pilot Limit in the Audi interface.

any ideas?

**Comment by jeremypoulter** [comment]
Would you happen to have anything that can / the ability to measure the duty cycle of the pilot signal?

**Comment by dmelliott20** [comment]
I think my multimeter has that function.

Leave it with me and I’ll do some tests.

Dave

On 1 Apr 2023, at 21:16, Jeremy Poulter ***@***.***> wrote:

﻿

Would you happen to have anything that can / the ability to measure the duty cycle of the pilot signal?

**Comment by jeremypoulter** [comment]
Great, FYI <https://openevse.dozuki.com/Guide/Testing+Basic+and+Advanced/12#s87>

**Comment by dmelliott20** [comment]
Yeah so it appears I’m short on duty cycles


16amp 23.9%

20amp 30.6%

32amp 50.5%

This is the official evse euro kit build too.

Dave

On 1 Apr 2023, at 23:07, Jeremy Poulter ***@***.***> wrote:

﻿

Great, FYI https://openevse.dozuki.com/Guide/Testing+Basic+and+Advanced/12#s87

**Comment by jeremypoulter** [comment]
Thanks, they do indeed seem to be out. I will check on my unit to see if I see the same. What OpenEVSE firmware do you have installed?

**Comment by dmelliott20** [comment]
Here’s the details…..

this is the unit I purchased https://shop.openenergymonitor.com/openevse-wifi-ev-charging-station-7kw-european-kit/

![9881017E-2B4C-45AB-93CE-F60CD412EE3A](https://user-images.githubusercontent.com/13154453/229368131-f2d060b0-e2c1-42d9-8b53-ccd4e78168f6.jpeg)

**Comment by dmelliott20** [comment]
Thank you, Let me know if I need to test anything further.

**Comment by glynhudson** [comment]
Interesting, I'm running controller FW V8.2.1 which is identical to V8.2.2 apart from the front push button not being enabled on all builds, and I'm not able to replicate. I'm running UI V2, but this should not play any part in the pilot signal. 

![Screenshot 2023-04-03 22 35 40](https://user-images.githubusercontent.com/758844/229633708-3a492253-d386-4cfa-ac77-bc3f655139cd.png)
 
What EV are you charging? Are you able to test with a different EV?

**Comment by dmelliott20** [comment]
Yes since discovering it I’ve tried 4 other EV’s now. I’ve always noticed it charged both my audis at 29.5amps when set to 32 but I just assumed it was the cars. It wasn’t until I plugged in the new bmw that it displayed the limit on the dashboard of 29amp and I noticed.

assuming I’ve measured right too. I just measured from cp to ground?

**Comment by ruddenchaux** [comment]
@glynhudson a similar issue was reported on https://community.openenergymonitor.org/t/nissan-leaf-pilot-signal-not-being-followed/22584 where the tested EV are a Nissan Leaf and Hyundai Kona.

**Comment by dmelliott20** [comment]
Yes that’s the exact same issue I’m having.

**Comment by glynhudson** [comment]
Thanks for testing, that's very useful. I will investigate further

**Comment by dmelliott20** [comment]
Thanks, to confirm tested on the following

Audi Etron GT
BMW I3
BMW ix3
Audi Etron sportback
Jaguar Ipace

all show the same result within 0.5amps

**Comment by dmelliott20** [comment]
@glynhudson are you testing on the same hardware as I have detailed above?

**Comment by dmelliott20** [comment]
Yes same behaviour...

![image](https://user-images.githubusercontent.com/13154453/229914464-8e1084cd-e271-4d5a-965e-8e1685cf5a78.png)

**Comment by dmelliott20** [comment]
Closing this issue as it was down to faulty hardware.

swapping out the openevse board fixed the problem.

thanks everyone
