### ISSUE TITLE
OpenEVSE nuisance trips, only when PV production is high

### ISSUE THREAD

**Issue by Jeedomguy** [OpenEVSE/ESP32_WiFi_V4.x#591]
Hello,

I bought an Open EVSE Advanced Series Kit one year ago, and it works pretty well so far, except for an issue that I can't solve:
I'm trying to charge as much as possible when my rooftop PV is producing, but I experience charger tripping when the PV production is very high (above 2500W for an installation of 4500Wp).
The charger never trips at other moment. 
Everything goes well when charging at night.
Everything goes well during the day when the PV production is low.
Nuisance trips happens only when the PV production is high.
I tried to open the circuit breaker of the PV system to see if it solves the issues immediately after, but the problem remains.

I looked at the logs, but nothing. 
The logs show that the status switch from "Charging" for 30 to 60 seconds, then "EV Connected" for 10 to 20 sec, then "Charging" again for 30 to 60 sec, and so on 4 or 5 times until it stops trying and stays in "EV Connected".
There is no message issues appearing on the car (Renault Zoe from 2017).

Do you think there could be voltage issues or earth issues on my network when PV is at full power, but without appearing on OPENEVSE logs?

See the logs attached showing the sequence.

Thanks in advance for your help.

![OpenEVSE](https://user-images.githubusercontent.com/129626285/229313604-d8db458d-1fc8-4b33-a12f-60df4be48d83.jpg)

**Comment by glynhudson** [comment]
Can you check to see if there is an error message displayed on the LCD when the unit trips?

**Comment by Jeedomguy** [comment]
No there is no error message displayed on the LCD.
Note that I hear a slight noise/vibration in the charger when it's in charging mode. Not sure if that can be linked or not.
________________________________
De : Glyn Hudson ***@***.***>
Envoyé : dimanche 2 avril 2023 02:58
À : OpenEVSE/ESP32_WiFi_V4.x ***@***.***>
Cc : Jeedomguy ***@***.***>; Author ***@***.***>
Objet : Re: [OpenEVSE/ESP32_WiFi_V4.x] OpenEVSE nuisance trips, only when PV production is high (Issue #591)


Can you check to see if there is an error message displayed on the LCD when the unit trips?

**Comment by Jeedomguy** [comment]
Hello,

I'm not using Divert mode.
I'm using my Home Assistant (an open source one called "Jeedom") which monitors the PV production every minute, and send a new charging power command to OpenEVSE accordingly.
See attached the chart and logs for the last 30 minutes where I had again 3 short disconnections.


Thanks,

Damien
________________________________
De : Guillaume S ***@***.***>
Envoyé : mardi 4 avril 2023 08:42
À : OpenEVSE/ESP32_WiFi_V4.x ***@***.***>
Cc : Jeedomguy ***@***.***>; Author ***@***.***>
Objet : Re: [OpenEVSE/ESP32_WiFi_V4.x] OpenEVSE nuisance trips, only when PV production is high (Issue #591)


do you have a graph of your published pv data used by divert mode ?
How is the frequency of the data publishing ? Are they coming in a regular interval ?

New input filter will handle non fixed sample rate, but current implemented one needs fresh data each 10sec.

May I see your divert parameters ?

**Comment by Jeedomguy** [comment]
[](url)
![OpenEVSE2](https://user-images.githubusercontent.com/129626285/230606942-e3451fdf-7f9f-4c3a-b8f7-7a832408f803.jpg)

**Comment by KipK** [comment]
Ok I see you use 4.1.7 it has a lot of wifi disconnection problem because a
bug with Mqtt. Can you try with latest dev build ( v2_gui ) and post a
screenshot the monitor/command tab when it trips out. And can you use the
export data from the Développer tab and post them too ?

I use Jeedom too. You can reach me on Jeedom community if needed.

**Comment by Jeedomguy** [comment]
Thanks Guillaume.
Let me that this weekend and until I get the issue again and I’ll update you with the logs.
Merci !
