### ISSUE TITLE
WPA3 Compatibility?

### ISSUE THREAD

**Issue by fhteagle** [OpenEVSE/ESP32_WiFi_V4.x#598]
Anybody know if the OpenEVSE_wifi_v1 hardware / firmware is capable of connecting to a WPA3 secured access point?

**Comment by KipK** [comment]
according to Espressif SDK it should works out of the box. Have you tried ?

**Comment by fhteagle** [comment]
Okay I ironed out the wrinkles in my hostapd setup, and the OpenEVSE Wifi V1 is now connected to my WPA3 only access point. So, compatibility confirmed.
