### ISSUE TITLE
Implement schedules for days / times?

### ISSUE THREAD

**Issue by Edison517** [OpenEVSE/ESP32_WiFi_V4.x#6]
I apologize if this request is being worked on already, but if so, I couldn't find it.

I'd like the ability to set schedules for charging by day, and time, multiple times per day (if possible).

I have time-of-use billing and I would rather have the schedule of cheap rates (mostly at night) done on my OpenEVSE rather than my 2014 Volt. I know that right now I can set a daily schedule, but that doesn't help me when my weekend rates are the same as my nightly rates during the week :)

**Comment by jeremypoulter** [comment]
This has partly been implemented as part of #5. The backend is a full 7-day timer with multiple events per day, just needs the UI updaing
