### ISSUE TITLE
Can not update from 4.19 to 4.2.2 with v2 gui

### ISSUE THREAD

**Issue by ausil** [OpenEVSE/ESP32_WiFi_V4.x#600]
I have two OpenEVSE's one is older and has a huzzah32 module in it and I have upgraded it to 4.2.2 just fine, I have a newer unit that has a openevse_wifi_v1 module and when I click on upgrade nothing happens.  the changer sees the new firmware it just will not load up the window to upgrade

![image](https://user-images.githubusercontent.com/13894066/232355206-cf35a6b9-8fb8-4b77-b6b8-ef646b2f34b6.png)

**Comment by KipK** [comment]
That's a little bug on UI I have fixed since
You can upgrade using Curl command:

curl -F firmware=openevse_wifi_v1.bin http://openevsze.local/update --progress-bar | cat

**Comment by ausil** [comment]
```
$ curl -F firmware=openevse_wifi_v1.bin http://openevse2.ausil.us/update --progress-bar | cat
####################################################################################################################################################################################################################################### 100.0%curl: (56) Recv failure: Connection reset by peer
```
and still shows v4.1.9
