### ISSUE TITLE
Update questions around OpenEVSE v1 or v2 board?

### ISSUE THREAD

**Issue by j256** [OpenEVSE/ESP32_WiFi_V4.x#606]
I've got an OpenEVSE but I've got questions about updating.

Found "Firmware update" in the manual.  It mentions the bin files and I see the 4.2.2 which looks to be the stable release.  But I see v1-gui-v1 and v1-gui-v2 bin files but no description of what those are or how I determine which to use.  Maybe these are the old and the new version of the GUI for the v1 OpenEVSE Wifi board?

I can't see anything about v1 or v2 on the web interface itself.  I'm worried that I will brick my unit if I load v2 on a v1 or something.  I don't see a picture of a v2 for comparison?

Some help?  Thanks,

**Comment by KipK** [comment]
It's written at the top of the release description:
https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/tag/v4.2.2

**Comment by j256** [comment]
Thanks for the response @KipK .  I see the mention but I still have questions.
* How do I determine which one I have now?
* What are the differences?
* Is v2 some sort of UI upgrade?

**Comment by KipK** [comment]
V2 is new user interface. If you have it you would see it then, it's completely different
