### ISSUE TITLE
NTP not updating? 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#610]
How long should it take for NTP to update? I've connected a new openevse to a Wi-Fi network with internet connection after 30 min NTP has still not updated with correct time. How can I debug this? 

![Screenshot 2023-04-29 16 45 23](https://user-images.githubusercontent.com/758844/235312007-9b169212-7004-4209-895d-fe064747209f.png)

![Screenshot 2023-04-29 16 45 56](https://user-images.githubusercontent.com/758844/235312011-2fad82db-9a05-41b5-a9d6-f81affdfbf6e.png)

Running latest master version 

![Screenshot 2023-04-29 17 05 13](https://user-images.githubusercontent.com/758844/235312199-a20ed1a4-e421-42b5-8e65-26238071280d.png)

[6e8f5242dbb86e859ab26abc12576246596cf052](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/tree/6e8f5242dbb86e859ab26abc12576246596cf052)

**Comment by glynhudson** [comment]
Rolling back to V4.2.2 fixed the issue

**Comment by KipK** [comment]
What version was that?
