### ISSUE TITLE
Restart required after Wi-Fi connection to update NTP

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#621]
After connecting a new WiFi module to a WiFi network the module requires a restart before NTP will set the time. 

How long should it take for NTP to update? Possibly I didn't wait long enough, but I was waiting about 20-30s with no NTP update before restarting

Update: just waited several min and NTP has not connected without a restart, same issue on both WiFi and Etherent modules 

![Screenshot from 2023-05-03 13-32-49](https://user-images.githubusercontent.com/758844/235917152-887014eb-a663-46a4-bed4-85c4743cd1a3.png)
![Screenshot from 2023-05-03 13-32-42](https://user-images.githubusercontent.com/758844/235917158-012f315f-e89c-4b6d-91e7-bc4645494b82.png)

**Comment by KipK** [comment]
That's odd it's supposed to be instantaneous when you select NTP from the drop down selector.
When you switch from Manual to NTP doesn't it set correctly ? 

Does your EVSE got working DNS from dhcp over your wired network ?

**Comment by KipK** [comment]
#624 add a time event publish after ntp update. It was missing, it probably is the reason ( but time should have updated after 30 sec max in your previous test )

**Comment by KipK** [comment]
I think I should also move time setting after the wifi redirection step in the wizard but that doesn't explain your case with ethernet.

**Comment by glynhudson** [comment]
>That's odd it's supposed to be instantaneous when you select NTP from the drop down selector.

I've not touched the NTP selection since NTP is selected as default. 

>When you switch from Manual to NTP doesn't it set correctly ?

I've not tested this 

>Does your EVSE got working DNS from dhcp over your wired network ?

Yes, DHCP and wired connection works fine. I also experienced the same issue with WiFi module

**Comment by KipK** [comment]
can you merge #624 and test the generated daily gui-v2 build if it fixes it?

**Comment by KipK** [comment]
@glynhudson is it fixed ?
