### ISSUE TITLE
Pilot does not update in the web interface until reboot

### ISSUE THREAD

**Issue by omriasta** [OpenEVSE/ESP32_WiFi_V4.x#651]
The pilot (labelled "SetPoint") in the new web interface (see attached screenshot) does not update instantly when the value changes.
I am not sure if it actually changes or not on the device or if it's just the web interface. It appears that after restarting the wifi module the value updates to what was set (I am using the MQTT API to change this).
![Screenshot from 2023-05-19 13-39-37](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/11823048/e6869be6-5f6b-4bf1-b4d4-a21b917db291)

**Comment by KipK** [comment]
it all depends on how you have set the pilot. 
Looks to be misusage between UI and mqtt claims.
Can you post the mqtt command you use ? 

if you use /claim {"charge_current": value} then it has lower priority than manual, so if you already have some charge_current override there, this will take the priority
( you can check in monitoring / commands page what service is controlling charge_current property ( it should display mqtt if it has the lead ) 
if you use /override  {"charge_current": value}   it then use the same as on UI then.

**Comment by omriasta** [comment]
Sorry, should have mention I was using mqtt rapi.
So openevse/rapi/in/$SC 10 for example (I'm on my phone so not sure if I have a typo in the command).
I am not using claims or divert.

**Comment by KipK** [comment]
rapi is deprecated, don't use it, that's what it is messing up

**Comment by omriasta** [comment]
Got it, may want to completely disable that part...it's odd as it does take effect after a reboot

**Comment by KipK** [comment]
RAPI will be removed for next release in booth HTTP and MQTT, so it won't be confusing anymore.
