### ISSUE TITLE
OCPP Authentication key

### ISSUE THREAD

**Issue by rvoosterhout** [OpenEVSE/ESP32_WiFi_V4.x#653]
Hello,

Where in Steve can I find the Authentication Key? My openevse was a few versions behind, but now I need to fill in the authentication key.

Thanks.

**Comment by jeremypoulter** [comment]
@matth-x can you help?

**Comment by matth-x** [comment]
You can leave this field blank. SteVe doesn't support Basic Authentication (unfortunately).

The other fields can remain the same as in the previous version.

Please reopen if you have follow-up questions.

**Comment by KipK** [comment]
@matth-x oups I thought it was needed. I've made the password required on UI. I need to change that then. 
When I've tested I used the admin password as key and it worked. I don't remember If I have tried putting anything :)

**Comment by rvoosterhout** [comment]
Thanks for the quick fix!

**Comment by pir8radio** [comment]
did this get reverted?  I have tried to connect to several OCPP servers and none connect, (none use this auth key) so im not sure if thats messing things up?

![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/16748696/ee4a9eac-a9cd-4196-9b41-991998178a4a)

**Comment by matth-x** [comment]
In my latest tests everything worked as expected. The fix is inside the submodule `gui` and I could imagine the submodule is not checked out at the latest commit.

**Comment by pir8radio** [comment]
Either way I don't think this key should be "required" in future releases.
