### ISSUE TITLE
Openevse shows GUI shows manual after sending DELETE override

### ISSUE THREAD

**Issue by rvoosterhout** [OpenEVSE/ESP32_WiFi_V4.x#654]
OpenEVSE | 7.1.3 
OpenEVSE Wifi | v4.2.2

Hello,

I'm trying to remove the manual mode by sending an powershell command to remove the manual mode. I can see on the screen that the manual mode dissapears, but the GUI still shows manual mode enabled. How can I remove the manual mode?

$response = Invoke-WebRequest -Uri 'http://192.168.1.8/override' -Method DELETE

**Comment by KipK** [comment]
what gui version do you have v1 ( old interface green one ) or v2 ( new interface, blue one ) ? ( firmware file ending by _gui-v1 or _gui-v2 )

**Comment by rvoosterhout** [comment]
V2

**Comment by KipK** [comment]
> I can see on the screen that the manual mode dissapears, but the GUI still shows manual mode enabled

Can you post a screen ? I don't get it

**Comment by rvoosterhout** [comment]
I agree, I wasn't very clear. With the screen i meant the display on the openevse unit itself. The display shows manual override when you turn it to manual override. When I  clear the manual override by sending the powershell command mentioned above, or I use node red using an http request DELETE node, it does change the display on the unit itself, but on the GUI it still shows manual mode. It doesn't switch to automatic mode (the little robot icon). Clearing the manual override by sending the DELETE command actually toggles the charger to Enabled on manual override. It doens't remove the manual override.
![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/31246342/11f05cb0-189f-4080-9449-61d3a397e704)

**Comment by KipK** [comment]
If you talk about the little tag on the bottom left of the status bar, it doesn't always means there's  a manual override. If it is the default state, it will also display it is manual, if there's nothing else that control automatically the evse state. ( I could fix that and display somehting like "Default" )
It's because it considers it is in manual mode ( aka you have to click on charge or stop to trigger the action you want. )

If you want to check the claims/override go in monitoring/commands tab and you will see if there's one running.

**Comment by rvoosterhout** [comment]
The strange thing is, I used to have the 3rd middle button looking like a robot, where I could choose to have openevse automaticly decide what to do.
Let me also explain my situation. I'm using Node Red to disable the charger when i'm not home to prevent other people using it by sending an http request with the payload {"state": "disabled"} to enable the manual override and disable the charger. That works. But I want to disable the manual override when I get home and let openevse use the automatic mode with the shaper, but that doesn't seem to work.
In the following screenshot, I sent the http request DELETE to disable manual override, but it does the opposite, it activates the manual override without showing anything in Monitoring - commands
![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/31246342/45601fec-5887-46aa-a79e-79660e299fa2)

**Comment by KipK** [comment]
as you can see in your Monitoring screenshot there's no "state" property set by "manual" so no manual override. Everything is allright. 

Are you sure you are not using the current dev build ? And you have set the /config/EVSE/ Default State to Active ?

**Comment by KipK** [comment]
Also if robot icon appears, it means you have either some timers set or selfprod | ocpp enabled. Shaper is working in the backgrnd of all charge tasks, it won't activate alone the evse, but it will disable it if there's not enough power left in the powerwall. It is not really part of an automation but a security.

**Comment by rvoosterhout** [comment]
I'm not using the dev build at the moment. Where do I set the defaut state?

There is indeed no state propery set by manual in my monitoring, yet the display on my openevse unit shows manual override.

**Comment by KipK** [comment]
Default state is only on current build, but forget my question, I forgot default state is actually to Active. You will be able to set that on next release ( or current dev build ) 

for you display problem, perhaps it's just a bug with lcd. I got some frozen line on some other situations, like in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/597

**Comment by KipK** [comment]
You should forget the manual override term, with V2 gui there's no such thing. UX has changed. If you use any property in an /override , not only "state" one, I think it display manual_override on the lcd, 
That's something we need to rework a bit.

it also always report "manual_override: 1" on /status & mqtt. This property has no much sense now ( and should probably be deleted ). The complete /override should be fetched at version change.

**Comment by rvoosterhout** [comment]
I understand now, thank you for the explanation!

**Comment by KipK** [comment]
you're welcome. 
Talking about your use case makes me consider to always display the Auto ( robot ) button. It removes the state override, and will display the Default tag if there's nothing else so this makes sense now we have a configurable default state

**Comment by jeremypoulter** [comment]
It might make sense, the UI still has to interact with the override as the front panel button will do the same as the V1 UI, IE toggle override on/off so we either need to change that behaviour or handle it in the UI. IMHO it should be in 'auto' mode by default even if there aren't any special features setup

**Comment by KipK** [comment]
yes,  I have changed this in current master.  I was not a fan of the Auto button popping out of nowhere. Looks more consistant now, and keep the logic everywhere.
