### ISSUE TITLE
Api break

### ISSUE THREAD

**Issue by andig** [OpenEVSE/ESP32_WiFi_V4.x#675]
Looks like the `watthour` was changed from `int` to `float`, see https://github.com/evcc-io/evcc/issues/8401. I couldn't find a link to OAS documentation- could you kindly point to current downloadable api spec?

**Comment by jeremypoulter** [comment]
The API spec is in Git: https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/master/api.yml

**Comment by andig** [comment]
Thank you 🙏
