### ISSUE TITLE
Update directly from Github releases not available in latest master 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#677]
![Screenshot from 2023-06-12 18-00-16](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/758844/ba12a895-fd80-4326-a27a-d502ad848abe)

**Comment by KipK** [comment]
have you updated & built the gui first ? 
I have tested latest master and it works ok. Also dev builds from gh.

**Comment by glynhudson** [comment]
Ok, that's good to know. I was running the FW built by this github actions https://github.com/OpenEVSE/ESP32_WiFi_V4.x/actions/runs/5224050601
