### ISSUE TITLE
Sensor voltage always shows 240V, not actual voltage

### ISSUE THREAD

**Issue by TechnicalLee** [OpenEVSE/ESP32_WiFi_V4.x#678]
The voltage reading on the Monitoring > Sensors page does not update to reflect the actual voltage. In Level 1 it will always says 120V and on Level 2 it will always say 240V without ever changing.

**Comment by jeremypoulter** [comment]
The voltage is only a constant as there is no voltage monitoring hardware. You can feed in there voltage via MQTT if you want more accurate power readings

**Comment by TechnicalLee** [comment]
OK, then I'd propose removing it from the "sensors" page if the voltage isn't actually being sensed. It should only be visible if MQTT is being used then. Placeholder values are confusing to the user when mixed with actual live data.
