### ISSUE TITLE
solar production management

### ISSUE THREAD

**Issue by monfiston** [OpenEVSE/ESP32_WiFi_V4.x#683]
Good morning
I note that when using solar mode, the evse terminal changes the intensity values, but there are always around 300/400w which are reinjected into the electricity network instead of going into the car

here is my setup
[export.json.zip](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/files/11897929/export.json.zip)
![configuration](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/109015014/71bcfcff-b6e0-4392-ae8d-23c67cee41c1)

here is an example, but I have many others
in blue the consumption curve of my house which is positive when I consume current, and negative when I send current to the national electricity grid
and in orange the openevse intensity setpoint
![consigne](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/109015014/e5c499ee-4dc8-4350-8bad-4a887e6e0da2)
as you can see for almost 1 hour, I sent back to the electrical network 300w on average constantly

here is the same graph all day
![consigne 1](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/109015014/12a5c2bb-4aac-4b52-98ce-2c3438df89d1)

is it possible to improve the algorithm to avoid sending electricity into the network?

**Comment by KipK** [comment]
@monfiston is the issue solved on your side?

**Comment by monfiston** [comment]
Non, mais je pense que le pb provient de mon interface openevse(copie de mauvaise qualité)
