### ISSUE TITLE
Add Vehicle Config UI Tab and SoC display 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#71]
After https://github.com/OpenEVSE/ESP32_WiFi_V3.x/pull/67 is merged we should make a 'Vehicle' tab on the web UI interface to interface with the Tesla integration e.g set enter username / password etc. I've added the API call for the Tesla integration as a comment in #67 

The vehicle tab should be structured to allow for multiple vehicle integrations, probably with only a single integration being used at a time..for the moment.  

Once the vehicle integration is active the current vehicle SoC can be displayed on the main page, it would probably be a good idea to provide an indicator as to when this was last updated (like we currently with solar PV divert). 

OVMS should be the next integration to consider adding.

**Comment by Pukkahq** [comment]
I have not tested this in the last few years but this might help for the BMW
https://github.com/openenergymonitor/emonhub/tree/emon-pi/conf/interfacer_examples/bmw

**Comment by Pukkahq** [comment]
just been and added the interface yes it still works
![image](https://user-images.githubusercontent.com/15746724/80316784-ad286900-87f7-11ea-8130-eba621c255bc.png)

**Comment by glynhudson** [comment]
The GUI looks great, however where is the MQTT topic for SoC set? Or is this pre-set to a particular topic? If this is the case the GUI should have an info box to let the user know what topic to use for SoC 

![Selection_004](https://user-images.githubusercontent.com/758844/126671248-a7e2ab0f-e2ae-47f2-b9d7-e5a3294261da.jpg)

**Comment by jeremypoulter** [comment]
Not quite sure I understand the issue, your screen shot has the input field for the SoC topic, is it not clear that you should enter a topic name?

**Comment by glynhudson** [comment]
Apologies, my mistake, I didn't realise the fields where for topic names. I figured it out, working now :-) 

To make it obvious I've added the word  'topic' as a suffix to the field labels: https://github.com/OpenEVSE/openevse_wifi_gui/commit/a50ad7706d1e2a69c532c3f3704ff16a5e304fe9

![Screenshot 2021-07-22 23 25 53](https://user-images.githubusercontent.com/758844/126717494-bce0193b-4093-4770-ad34-0313ec9a4e04.png)

![Screenshot 2021-07-22 23 26 05](https://user-images.githubusercontent.com/758844/126717523-bc1c0906-1492-4145-b134-73e11d5a4f49.png)
